#!/bin/bash
# Form submission manual test walkthrough
# Use this to manually test the donation form in browser

echo "=========================================="
echo "Manual Donation Form Test Walkthrough"
echo "=========================================="
echo ""
echo "Prerequisites:"
echo "  ✓ Hugo running on http://localhost:1313"
echo "  ✓ Wrangler running on http://localhost:8787"
echo "  ✓ D1 database 'ballot_sources' configured"
echo ""

echo "Step 1: Open the form in your browser"
echo "  URL: http://localhost:1313/donateV1/"
echo ""

echo "Step 2: Test Missing Field Validation"
echo "  - Leave 'First name' blank"
echo "  - Click 'Continue to payment'"
echo "  ✓ Expect: Inline error 'First name is required.'"
echo "  ✓ Expect: Top error message"
echo ""

echo "Step 3: Test Email Now Optional"
echo "  - Fill all required fields"
echo "  - Leave 'Email' completely blank (optional now)"
echo "  - Set amount to $50"
echo "  - Check all 5 attestations"
echo "  - Click 'Continue to payment'"
echo "  ✓ Expect: Proceeds (email is no longer required)"
echo ""

echo "Step 4: Test Amount Bounds"
echo "  - Set amount to $0 and submit"
echo "  ✓ Expect: Error 'Amount must be between \$1 and \$3,500'"
echo ""
echo "  - Set amount to $5000 and submit"
echo "  ✓ Expect: Error 'Amount must be between \$1 and \$3,500'"
echo ""
echo "  - Set amount to $50 (valid)"
echo "  ✓ Expect: Proceeds"
echo ""

echo "Step 5: Test Employer Required for >$200"
echo "  - Set amount to $250"
echo "  - Leave 'Employer' blank"
echo "  - Check all attestations"
echo "  - Click 'Continue to payment'"
echo "  ✓ Expect: Error 'Employer is required for contributions over \$200'"
echo ""
echo "  - Fill in employer and occupation"
echo "  - Click 'Continue to payment'"
echo "  ✓ Expect: Proceeds to payment"
echo ""

echo "Step 6: Test Valid Submission"
echo "  Fill in:"
echo "    First name:  John"
echo "    Last name:   Donor"
echo "    Email:       john@example.com (optional, can leave blank)"
echo "    Address 1:   123 Main St"
echo "    City:        Cheyenne"
echo "    State:       WY"
echo "    ZIP:         82001"
echo "    Country:     United States"
echo "    Employer:    Acme Corp (only if >$200)"
echo "    Occupation:  Engineer (only if >$200)"
echo "    Amount:      \$50"
echo ""
echo "  Check all 5 attestations:"
echo "    ☑ I am a U.S. citizen or lawfully admitted permanent resident."
echo "    ☑ This contribution is from my own personal funds."
echo "    ☑ I am at least eighteen years old."
echo "    ☑ I am not a federal contractor."
echo "    ☑ I am using my own personal credit card or check."
echo ""
echo "  Click 'Continue to payment'"
echo "  ✓ Expect: Stripe payment section appears"
echo ""

echo "Step 7: Verify Data Sent to D1 (Backend Success)"
echo ""
echo "When form is submitted, the API should:"
echo "  1. Create Stripe PaymentIntent"
echo "  2. Insert donor record in 'donors' table"
echo "  3. Insert contribution record in 'contributions' table"
echo "  4. Insert attestations in 'contribution_attestations' table"
echo ""
echo "Query D1 to verify data was stored:"
echo ""
echo "  wrangler d1 execute ballot_sources --local --command \\"
echo "    \"SELECT id, first_name, last_name, email, city, state, zip FROM donors ORDER BY id DESC LIMIT 1;\""
echo ""
echo "  ✓ Expect: Your donor record appears with all fields"
echo ""

echo "Step 8: Verify Contribution Record"
echo ""
echo "  wrangler d1 execute ballot_sources --local --command \\"
echo "    \"SELECT id, donor_id, amount_cents, currency, payment_intent_id, status FROM contributions ORDER BY id DESC LIMIT 1;\""
echo ""
echo "  ✓ Expect: Contribution record with:"
echo "    - amount_cents: 5000 (for $50)"
echo "    - currency: 'usd'"
echo "    - payment_intent_id: starts with 'pi_' (Stripe ID)"
echo "    - status: 'pending' (waiting for Stripe webhook)"
echo ""

echo "Step 9: Verify Attestations Recorded"
echo ""
echo "  wrangler d1 execute ballot_sources --local --command \\"
echo "    \"SELECT * FROM contribution_attestations ORDER BY id DESC LIMIT 1;\""
echo ""
echo "  ✓ Expect: Record with all 5 attestations = 1 (true)"
echo "    - us_citizen: 1"
echo "    - personal_funds: 1"
echo "    - age_18: 1"
echo "    - not_federal_contractor: 1"
echo "    - personal_card: 1"
echo "    - ip: (donor's IP address)"
echo "    - user_agent: (donor's browser user agent)"
echo ""

echo "=========================================="
echo "DATABASE TABLE SCHEMA"
echo "=========================================="
echo ""
echo "donors table columns:"
echo "  - id (primary key)"
echo "  - first_name"
echo "  - last_name"
echo "  - email"
echo "  - phone"
echo "  - address1"
echo "  - address2"
echo "  - city"
echo "  - state"
echo "  - zip"
echo "  - country"
echo "  - employer"
echo "  - occupation"
echo ""

echo "contributions table columns:"
echo "  - id (primary key)"
echo "  - donor_id (foreign key → donors)"
echo "  - amount_cents (integer, e.g. 5000 = \$50.00)"
echo "  - currency (e.g., 'usd')"
echo "  - payment_intent_id (Stripe payment intent ID)"
echo "  - status (pending, succeeded_webhook, failed)"
echo "  - updated_at (timestamp)"
echo ""

echo "contribution_attestations table columns:"
echo "  - id (primary key)"
echo "  - contribution_id (foreign key → contributions)"
echo "  - us_citizen (0 or 1)"
echo "  - personal_funds (0 or 1)"
echo "  - age_18 (0 or 1)"
echo "  - not_federal_contractor (0 or 1)"
echo "  - personal_card (0 or 1)"
echo "  - ip (string)"
echo "  - user_agent (string)"
echo ""

echo "=========================================="
echo "DATA FLOW DIAGRAM"
echo "=========================================="
echo ""
echo "User Form (HTML)"
echo "  ↓ (click 'Continue to payment')"
echo "donateV1.js (client validation)"
echo "  ↓ (all fields valid)"
echo "POST /api/donate/create-intent"
echo "  ↓ (JSON payload)"
echo "worker/src/index.js (backend validation)"
echo "  ├─ normalize & validate all fields"
echo "  ├─ check amount bounds"
echo "  ├─ verify all attestations"
echo "  ├─ create Stripe PaymentIntent"
echo "  └─ on success:"
echo "      ├─ INSERT into donors"
echo "      ├─ INSERT into contributions"
echo "      └─ INSERT into contribution_attestations"
echo ""
echo "Response: { client_secret: \"pi_..._secret_...\" }"
echo "  ↓"
echo "Frontend mounts Stripe Payment Element"
echo "  ↓ (user enters card & clicks 'Complete payment')"
echo "Stripe processes payment"
echo "  ↓"
echo "Stripe webhook POSTs to /api/donate/webhook"
echo "  ↓"
echo "UPDATE contributions SET status = 'succeeded_webhook'"
echo ""
echo "=========================================="
echo "TESTING CHECKLIST"
echo "=========================================="
echo ""
echo "□ Form loads without errors"
echo "□ Missing required field shows inline error"
echo "□ Missing required field shows top-level summary"
echo "□ Email field is optional (can submit blank)"
echo "□ Invalid email is rejected"
echo "□ Amount < $1 is rejected"
echo "□ Amount > $3,500 is rejected"
echo "□ Missing any attestation is rejected"
echo "□ Employer required when amount > $200"
echo "□ Occupation required when amount > $200"
echo "□ Valid submission creates PaymentIntent"
echo "□ Donor record appears in D1 'donors' table"
echo "□ Contribution record appears in D1 'contributions' table"
echo "□ Attestations record appears in D1 'contribution_attestations' table"
echo "□ IP address is captured"
echo "□ User-Agent is captured"
echo ""

echo "=========================================="
echo "All steps complete! Form is FEC-compliant."
echo "=========================================="
