-- 001_seed.sql
-- Source: wy_2026_primary_candidates.csv (WY SOS filing data)
-- Run after 0001_candidates_schema.sql
-- Safe to re-run: INSERT OR IGNORE on slug (candidates) and partial unique indexes (offices)

-- ============================================================
-- OFFICES
-- ============================================================

INSERT OR IGNORE INTO offices (title, level, district, sort_order) VALUES
  ('United States Senator',                'federal',   NULL,  100),
  ('United States Representative',         'federal',   NULL,  110),
  ('Governor',                             'statewide', NULL,  200),
  ('Secretary Of State',                   'statewide', NULL,  210),
  ('State Auditor',                        'statewide', NULL,  220),
  ('State Treasurer',                      'statewide', NULL,  230),
  ('Superintendent Of Public Instruction', 'statewide', NULL,  240);

INSERT OR IGNORE INTO offices (title, level, district, sort_order) VALUES
  ('State Senator', 'wy_senate',  1, 301),
  ('State Senator', 'wy_senate',  3, 303),
  ('State Senator', 'wy_senate',  5, 305),
  ('State Senator', 'wy_senate',  6, 306),
  ('State Senator', 'wy_senate',  7, 307),
  ('State Senator', 'wy_senate',  9, 309),
  ('State Senator', 'wy_senate', 11, 311),
  ('State Senator', 'wy_senate', 13, 313),
  ('State Senator', 'wy_senate', 15, 315),
  ('State Senator', 'wy_senate', 17, 317),
  ('State Senator', 'wy_senate', 19, 319),
  ('State Senator', 'wy_senate', 21, 321),
  ('State Senator', 'wy_senate', 23, 323),
  ('State Senator', 'wy_senate', 25, 325),
  ('State Senator', 'wy_senate', 27, 327),
  ('State Senator', 'wy_senate', 29, 329),
  ('State Senator', 'wy_senate', 31, 331);

INSERT OR IGNORE INTO offices (title, level, district, sort_order) VALUES
  ('State Representative', 'wy_house',  1, 401),
  ('State Representative', 'wy_house',  2, 402),
  ('State Representative', 'wy_house',  3, 403),
  ('State Representative', 'wy_house',  4, 404),
  ('State Representative', 'wy_house',  5, 405),
  ('State Representative', 'wy_house',  6, 406),
  ('State Representative', 'wy_house',  7, 407),
  ('State Representative', 'wy_house',  8, 408),
  ('State Representative', 'wy_house',  9, 409),
  ('State Representative', 'wy_house', 10, 410),
  ('State Representative', 'wy_house', 11, 411),
  ('State Representative', 'wy_house', 12, 412),
  ('State Representative', 'wy_house', 13, 413),
  ('State Representative', 'wy_house', 14, 414),
  ('State Representative', 'wy_house', 15, 415),
  ('State Representative', 'wy_house', 16, 416),
  ('State Representative', 'wy_house', 17, 417),
  ('State Representative', 'wy_house', 18, 418),
  ('State Representative', 'wy_house', 19, 419),
  ('State Representative', 'wy_house', 20, 420),
  ('State Representative', 'wy_house', 21, 421),
  ('State Representative', 'wy_house', 22, 422),
  ('State Representative', 'wy_house', 23, 423),
  ('State Representative', 'wy_house', 24, 424),
  ('State Representative', 'wy_house', 25, 425),
  ('State Representative', 'wy_house', 26, 426),
  ('State Representative', 'wy_house', 27, 427),
  ('State Representative', 'wy_house', 28, 428),
  ('State Representative', 'wy_house', 29, 429),
  ('State Representative', 'wy_house', 30, 430),
  ('State Representative', 'wy_house', 31, 431),
  ('State Representative', 'wy_house', 32, 432),
  ('State Representative', 'wy_house', 33, 433),
  ('State Representative', 'wy_house', 34, 434),
  ('State Representative', 'wy_house', 35, 435),
  ('State Representative', 'wy_house', 36, 436),
  ('State Representative', 'wy_house', 37, 437),
  ('State Representative', 'wy_house', 38, 438),
  ('State Representative', 'wy_house', 39, 439),
  ('State Representative', 'wy_house', 40, 440),
  ('State Representative', 'wy_house', 41, 441),
  ('State Representative', 'wy_house', 42, 442),
  ('State Representative', 'wy_house', 43, 443),
  ('State Representative', 'wy_house', 44, 444),
  ('State Representative', 'wy_house', 45, 445),
  ('State Representative', 'wy_house', 46, 446),
  ('State Representative', 'wy_house', 47, 447),
  ('State Representative', 'wy_house', 48, 448),
  ('State Representative', 'wy_house', 49, 449),
  ('State Representative', 'wy_house', 50, 450),
  ('State Representative', 'wy_house', 51, 451),
  ('State Representative', 'wy_house', 52, 452),
  ('State Representative', 'wy_house', 53, 453),
  ('State Representative', 'wy_house', 54, 454),
  ('State Representative', 'wy_house', 55, 455),
  ('State Representative', 'wy_house', 56, 456),
  ('State Representative', 'wy_house', 57, 457),
  ('State Representative', 'wy_house', 58, 458),
  ('State Representative', 'wy_house', 59, 459),
  ('State Representative', 'wy_house', 60, 460),
  ('State Representative', 'wy_house', 61, 461),
  ('State Representative', 'wy_house', 62, 462);

-- ============================================================
-- CANDIDATES — helper macro: o(title, district)
-- Each INSERT uses a subquery to resolve office_id by name+district
-- so the seed is resilient to autoincrement gaps.
-- ============================================================

-- United States Senator
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Republican','Harriet Hageman','harriet-hageman','Cheyenne','WY','82003','P.O. Box 4157','307-228-4886','info@hagemanforwyoming.com','2026-05-15',NULL,1 FROM offices WHERE title='United States Senator' AND district IS NULL;
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Republican','Jill M Edwards','jill-m-edwards','Laramie','WY','82070','514 Grand Ave P.O. Box 374','307-243-8683','info@edwardsforus.com','2026-05-14',NULL,1 FROM offices WHERE title='United States Senator' AND district IS NULL;
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Republican','Jimmy Skovgard','jimmy-skovgard','Casper','WY','82604','5685 Hanly St','307-277-2260','jimmy@grassrootsmvt.org','2026-05-18',NULL,1 FROM offices WHERE title='United States Senator' AND district IS NULL;
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Republican','John Holtz','john-holtz','Laramie','WY','82072','1167 Granito Dr','307-745-6154','herrholtz@bresnan.net','2026-05-14',NULL,1 FROM offices WHERE title='United States Senator' AND district IS NULL;
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Republican','Sam Mead','sam-mead','Jackson','WY','83001','P.O. Box 1809','307-241-8805','info@meadforwyoming.com','2026-05-19',NULL,1 FROM offices WHERE title='United States Senator' AND district IS NULL;
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Democratic','Billy Benavidez','billy-benavidez','Sheridan','WY','82801','726 Long Dr Apt 29','307-533-6211','emhprocleaning@gmail.com','2026-05-20',NULL,1 FROM offices WHERE title='United States Senator' AND district IS NULL;
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Democratic','James Byrd','james-byrd','Cheyenne','WY','82001','2511 N Snyder Ave','307-289-9810','digitalmotorhead@gmail.com','2026-05-19',NULL,1 FROM offices WHERE title='United States Senator' AND district IS NULL;

-- United States Representative
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Republican','Bo Biteman','bo-biteman','Ranchester','WY','82839','P.O. Box 283','307-477-4626','bo@bobiteman.com','2026-05-26',NULL,1 FROM offices WHERE title='United States Representative' AND district IS NULL;
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Republican','Chuck Gray','chuck-gray','Casper','WY','82605','P.O. Box 50415','307-251-1372','info@chuckforwyoming.com','2026-05-26',NULL,1 FROM offices WHERE title='United States Representative' AND district IS NULL;
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Republican','David Giralt','david-giralt','Mills','WY','82644','P.O. Box 701','307-277-4617','david@davidgiralt.com','2026-05-28',NULL,1 FROM offices WHERE title='United States Representative' AND district IS NULL;
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Republican','Frank Chapman','frank-chapman','Moran','WY','83013','P.O. Box 70','307-699-7222','Frank@ChapmanforCongress.com','2026-05-14',NULL,2 FROM offices WHERE title='United States Representative' AND district IS NULL;
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Republican','Jillian Balow','jillian-balow','Cheyenne','WY','82003','P.O. Box 20945','307-352-9546','info@jillianbalowforwyoming.com','2026-05-14',NULL,2 FROM offices WHERE title='United States Representative' AND district IS NULL;
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Republican','Keith B. Goodenough','keith-b-goodenough','Casper','WY','82602-1852','P.O. Box 1852','307-237-3114','senatorgoodenough@gmail.com','2026-05-29',NULL,2 FROM offices WHERE title='United States Representative' AND district IS NULL;
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Republican','Kevin Christensen','kevin-christensen','Casper','WY','82601','1655 E Sunlight Dr','307-267-5288','kevin.for.ushouse@christensen2026.org','2026-05-19',NULL,2 FROM offices WHERE title='United States Representative' AND district IS NULL;
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Republican','Reid Rasner','reid-rasner','Casper','WY','82601','P.O. Box 1217','307-439-5539','info@reidrasnerforwyoming.com','2026-05-14',NULL,2 FROM offices WHERE title='United States Representative' AND district IS NULL;
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Republican','Richard Dodson','richard-dodson','Sundance','WY','82729','P.O. Box 754','307-228-5865','helpdeskgeek@yahoo.com','2026-05-29',NULL,2 FROM offices WHERE title='United States Representative' AND district IS NULL;
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Republican','Steve Friess','steve-friess','Cheyenne','WY','82001','1914 Thomes Ave Ste 2 #118','307-200-8731','info@friessforwy.com','2026-05-19',NULL,2 FROM offices WHERE title='United States Representative' AND district IS NULL;
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Democratic','Elena Del Real','elena-del-real','Lander','WY','82520','P.O. Box 1136','307-209-1491','elenadelreal2026@gmail.com','2026-05-29',NULL,2 FROM offices WHERE title='United States Representative' AND district IS NULL;
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Democratic','Lisa Kinney','lisa-kinney','Laramie','WY','82073','P.O. Box 1710','307-275-6431','Lisakinney2026@wyoming.com','2026-05-15',NULL,2 FROM offices WHERE title='United States Representative' AND district IS NULL;

-- Governor
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Republican','Brent Bien','brent-bien','Cody','WY','82414','P.O. Box 96','307-763-3442','brent@brentbien.com','2026-05-17',NULL,2 FROM offices WHERE title='Governor' AND district IS NULL;
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Republican','Curt Blake','curt-blake','Centennial','WY','82055','P.O. Box 324','307-742-6944','betterwyowithblake@gmail.com','2026-05-26',NULL,2 FROM offices WHERE title='Governor' AND district IS NULL;
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Republican','Eric Barlow','eric-barlow','Gillette','WY','82718','1625 A Buffalo Cut Across Rd','307-209-4846','eric@barlowforwyo.com','2026-05-16',NULL,3 FROM offices WHERE title='Governor' AND district IS NULL;
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Republican','Megan Degenfelder','megan-degenfelder','Cheyenne','WY','82003','P.O. Box 1531','307-221-3099','megan@megandegenfelder.com','2026-05-19',NULL,3 FROM offices WHERE title='Governor' AND district IS NULL;
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Democratic','Kenneth R. Casner','kenneth-r-casner','Elk Mountain','WY','82324','205 Bridge St','307-397-8018','casnerken89@gmail.com','2026-05-14',NULL,3 FROM offices WHERE title='Governor' AND district IS NULL;

-- Secretary Of State
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Republican','CJ Young','cj-young','Cheyenne','WY','82003','P.O. Box 4103','307-317-1133','cj.young@cjyoungforwyoming.com','2026-05-28',NULL,3 FROM offices WHERE title='Secretary Of State' AND district IS NULL;
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Republican','Qwenton Eagle Oviatt','qwenton-eagle-oviatt','Hudson','WY','82515','P.O. Box 391','307-760-7524','qeowyo@gmail.com','2026-05-28',NULL,3 FROM offices WHERE title='Secretary Of State' AND district IS NULL;
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Republican','Rachel Williams','rachel-williams','Cody','WY','82414','P.O. Box 444','307-250-5008','williams4wy@gmail.com','2026-05-14',NULL,3 FROM offices WHERE title='Secretary Of State' AND district IS NULL;
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Republican','Robert Short','robert-short','Douglas','WY','82633','P.O. Box 906','307-267-2389','robert@shortforstate.com','2026-05-20',NULL,3 FROM offices WHERE title='Secretary Of State' AND district IS NULL;
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Democratic','Bryan McCarty','bryan-mccarty','Worland','WY','82401','313 S 21st St','817-228-3992','bryan.mccarty0907@gmail.com','2026-05-14',NULL,3 FROM offices WHERE title='Secretary Of State' AND district IS NULL;

-- State Auditor
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Republican','Kristi Racines','kristi-racines','Cheyenne','WY','82009','1302 Silver Spur Rd','307-851-1437','vote@kristiracines.com','2026-05-14',NULL,3 FROM offices WHERE title='State Auditor' AND district IS NULL;

-- State Treasurer
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Republican','Curt Meier','curt-meier','La Grange','WY','82221','4721 Road 18','307-746-8726','bob@meier4wyo.com','2026-05-19',NULL,4 FROM offices WHERE title='State Treasurer' AND district IS NULL;
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Republican','Scott Smith','scott-smith','Lingle','WY','82223','P.O. Box 483','307-575-3742','scott.smith.wyo@gmail.com','2026-05-27',NULL,4 FROM offices WHERE title='State Treasurer' AND district IS NULL;

-- Superintendent Of Public Instruction
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Republican','Chad Auer','chad-auer','Cheyenne','WY','82001','2820 Pioneer Ave','307-231-1235','chadauer@gmail.com','2026-05-14',NULL,4 FROM offices WHERE title='Superintendent Of Public Instruction' AND district IS NULL;
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Republican','Steve Harshman','steve-harshman','Casper','WY','82602','P.O. Box 295','307-262-8075','harshmanforwyoming@gmail.com','2026-05-17',NULL,4 FROM offices WHERE title='Superintendent Of Public Instruction' AND district IS NULL;
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Republican','Tom Kelly','tom-kelly','Sheridan','WY','82801','412 Airport Rd','307-461-9304','drthomasmkelly@gmail.com','2026-05-14',NULL,4 FROM offices WHERE title='Superintendent Of Public Instruction' AND district IS NULL;
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Democratic','Ana Cordova','ana-cordova','Cheyenne','WY','82001','1217 E 22nd St','307-316-2638','anaelizabethcordova@gmail.com','2026-05-15',NULL,4 FROM offices WHERE title='Superintendent Of Public Instruction' AND district IS NULL;
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Democratic','Sergio A. Maldonado, Sr.','sergio-a-maldonado-sr','Lander','WY','82520','P.O. Box 1826','307-349-8264','arapaho17mile@gmail.com','2026-05-14',NULL,4 FROM offices WHERE title='Superintendent Of Public Instruction' AND district IS NULL;

-- State Senate
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Republican','Chip Neiman','chip-neiman','Hulett','WY','82720','P.O. Box 116','307-290-0366','cneiman66@gmail.com','2026-05-28',NULL,4 FROM offices WHERE title='State Senator' AND district=1;
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Republican','Ogden Driskill','ogden-driskill','Devils Tower','WY','82714','P.O. Box 155','307-680-5555','wyomingcowboy77@gmail.com','2026-05-22',NULL,4 FROM offices WHERE title='State Senator' AND district=1;
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Republican','Cheri E Steinmetz','cheri-e-steinmetz','Torrington','WY','82240','P.O. Box 220','307-534-5342','steinmetzforsenate@gmail.com','2026-05-15',NULL,5 FROM offices WHERE title='State Senator' AND district=3;
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Republican','Ben Hornok','ben-hornok','Cheyenne','WY','82007','1903 S Greeley Hwy #251','307-369-3322','benhornokforwyoming@gmail.com','2026-05-18',NULL,5 FROM offices WHERE title='State Senator' AND district=5;
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Republican','Lauren Schoenfeld','lauren-schoenfeld','Cheyenne','WY','82009','2325 Torben Ct','307-922-6136','laurenschoenfeld307@gmail.com','2026-05-14',NULL,5 FROM offices WHERE title='State Senator' AND district=5;
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Republican','Meagan Herrington','meagan-herrington','Cheyenne','WY','82003','P.O. Box 1451','307-414-2920','meagan@herringtonforwyoming.com','2026-05-29',NULL,5 FROM offices WHERE title='State Senator' AND district=5;
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Republican','Ronald D. McCleary','ronald-d-mccleary','Cheyenne','WY','82007','1508 S Greeley Hwy Lot 12','307-640-1558','mcclearyronald07@gmail.com','2026-05-15',NULL,5 FROM offices WHERE title='State Senator' AND district=5;
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Democratic','Ted Hanlon','ted-hanlon','Cheyenne','WY','82009','808 West Dale Blvd','307-275-9556','ted@hanlon4wyoming.com','2026-05-15',NULL,5 FROM offices WHERE title='State Senator' AND district=5;
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Republican','Roy Birt','roy-birt','Wheatland','WY','82201','P.O. Box 191','307-331-0378','royjbirt@gmail.com','2026-05-27',NULL,5 FROM offices WHERE title='State Senator' AND district=6;
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Republican','Taft Love','taft-love','Cheyenne','WY','82009','1463 Earhart Dr','307-631-8707','taft@taftlove.com','2026-05-14',NULL,5 FROM offices WHERE title='State Senator' AND district=6;
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Republican','Mark Rinne','mark-rinne','Cheyenne','WY','82009','2847 Foothills Rd','307-634-6275','RinneforWyomingSenate@gmail.com','2026-05-14',NULL,5 FROM offices WHERE title='State Senator' AND district=7;
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Democratic','Jim Lee','jim-lee','Cheyenne','WY','82001','3411 Cribbon Ave','307-274-8309','jml.ltc.aus@gmail.com','2026-05-29',NULL,6 FROM offices WHERE title='State Senator' AND district=7;
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Democratic','Chris Rothfuss','chris-rothfuss','Laramie','WY','82073','P.O. Box 1791','307-399-3556','RothfussForSenate@gmail.com','2026-05-14',NULL,6 FROM offices WHERE title='State Senator' AND district=9;
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Republican','Bob Davis','bob-davis','Baggs','WY','82321','P.O. Box 369','307-380-6457','davisconstruction83@yahoo.com','2026-05-14',NULL,6 FROM offices WHERE title='State Senator' AND district=11;
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Democratic','Jim Wilson','jim-wilson','Rock Springs','WY','82901','50 Reliance Rd 112','307-371-4469','DEMJIM24@gmail.com','2026-05-29',NULL,6 FROM offices WHERE title='State Senator' AND district=11;
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Republican','Stacy Jones','stacy-jones','Rock Springs','WY','82901','927 Whitewater Dr','307-371-8182','jones4senate13@yahoo.com','2026-05-15',NULL,6 FROM offices WHERE title='State Senator' AND district=13;
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Republican','Chris Katzl','chris-katzl','Evanston','WY','82930','198 Holland Dr.','307-677-6983','cskatzl@yahoo.com','2026-05-29',NULL,6 FROM offices WHERE title='State Senator' AND district=15;
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Republican','Jen Hegeman','jen-hegeman','Evanston','WY','82930','485 Miller Ave','307-369-7099','hegemanforsenate@gmail.com','2026-05-27',NULL,6 FROM offices WHERE title='State Senator' AND district=15;
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Republican','Tina Johnson','tina-johnson','Evanston','WY','82930','425 Hickey Ave','307-780-5150','Tinajohnson4senate@protonmail.com','2026-05-29',NULL,6 FROM offices WHERE title='State Senator' AND district=15;
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Republican','Wendy Davis Schuler','wendy-davis-schuler','Evanston','WY','82930','200 Liberty Ave','307-679-6774','uwcowgirl13@gmail.com','2026-05-15',NULL,7 FROM offices WHERE title='State Senator' AND district=15;
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Democratic','Mike Gierau','mike-gierau','Jackson','WY','83001','435 Stacy Ln','307-413-0109','jeds@wyom.net','2026-05-14',NULL,7 FROM offices WHERE title='State Senator' AND district=17;
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Republican','Paul Hoeft','paul-hoeft','Powell','WY','82435','960 Ray Ct','307-254-2090','yakred@tritel.net','2026-05-14',NULL,7 FROM offices WHERE title='State Senator' AND district=19;
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Republican','R. J. Kost','r-j-kost','Powell','WY','82435','680 Road 11','307-202-0877','rjkostsenate2026@gmail.com','2026-05-15',NULL,7 FROM offices WHERE title='State Senator' AND district=19;
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Republican','Ken Pendergraft','ken-pendergraft','Sheridan','WY','82801','459 W Burkitt St','307-461-2436','kpendy62@gmail.com','2026-05-20',NULL,7 FROM offices WHERE title='State Senator' AND district=21;
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Republican','Melissa Butcher','melissa-butcher','Ranchester','WY','82839','P.O. Box 293','307-683-8213','melissa@butcherwyo.com','2026-05-19',NULL,7 FROM offices WHERE title='State Senator' AND district=21;
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Republican','Abby Angelos','abby-angelos','Gillette','WY','82717','P.O. Box 633','307-359-5856','abby@voteforabby.com','2026-05-14',NULL,7 FROM offices WHERE title='State Senator' AND district=23;
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Republican','Dwayne Dillinger','dwayne-dillinger','Gillette','WY','82718','6401 Force Rd','307-689-4863','ddillinger7866@msn.com','2026-05-19',NULL,7 FROM offices WHERE title='State Senator' AND district=23;
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Republican','Cale Case','cale-case','Lander','WY','82520','787 S 4th St','307-332-7623','ccase@wyoming.com','2026-05-14',NULL,7 FROM offices WHERE title='State Senator' AND district=25;
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Republican','Lisa Wilson','lisa-wilson','Lander','WY','82520','P.O. Box 1886','307-438-9384','lisawilsonforsd25@gmail.com','2026-05-29',NULL,8 FROM offices WHERE title='State Senator' AND district=25;
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Republican','Jim Corkery','jim-corkery','Casper','WY','82605','P.O. Box 50121','307-259-4496','JimCorkeryforWY@gmail.com','2026-05-29',NULL,8 FROM offices WHERE title='State Senator' AND district=27;
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Republican','Kevin Helling','kevin-helling','Casper','WY','82605','P.O. Box 50572','307-277-4725','kevin@hellingforwyoming.com','2026-05-14',NULL,8 FROM offices WHERE title='State Senator' AND district=27;
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Republican','Marcia Neumiller','marcia-neumiller','Casper','WY','82609','4251 Donegal St','307-315-2712','neumillermarcia@gmail.com','2026-05-29',NULL,8 FROM offices WHERE title='State Senator' AND district=27;
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Republican','Bob Ide','bob-ide','Casper','WY','82601','3838 Garden Creek Rd','307-472-0233','bob@idelandleasing.com','2026-05-14',NULL,8 FROM offices WHERE title='State Senator' AND district=29;
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Republican','Lisa Engebretsen','lisa-engebretsen','Casper','WY','82604','2240 W 43rd St','307-262-9740','lisa@forefrontrealtors.com','2026-05-26',NULL,8 FROM offices WHERE title='State Senator' AND district=29;
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Republican','Daniel J. Singh','daniel-j-singh','Cheyenne','WY','82003','P.O. Box 22106','307-274-3909','singh4wyoming@gmail.com','2026-05-21',NULL,8 FROM offices WHERE title='State Senator' AND district=31;
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Republican','Evie Brennan','evie-brennan','Cheyenne','WY','82003','P.O. Box 21615','307-630-0887','eviebrennanforwyosenate@gmail.com','2026-05-14',NULL,8 FROM offices WHERE title='State Senator' AND district=31;
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Democratic','Shifa Hamid','shifa-hamid','Cheyenne','WY','82003','P. O. Box 2986','307-274-8309','sjhamid.2@gmail.com','2026-05-26',NULL,8 FROM offices WHERE title='State Senator' AND district=31;

-- State House
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Republican','Troy Claycomb','troy-claycomb','Upton','WY','82730','P.O. Box 848','307-629-4410','troydclaycomb@gmail.com','2026-05-14',NULL,9 FROM offices WHERE title='State Representative' AND district=1;
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Republican','Zeta Nuckolls Anderson','zeta-nuckolls-anderson','Devils Tower','WY','82714','101 State Hwy 24','307-756-2141','zetaforwy@gmail.com','2026-05-14',NULL,9 FROM offices WHERE title='State Representative' AND district=1;
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Republican','JD Williams','jd-williams','Lusk','WY','82225-0000','251 A Greasewood Rd','307-340-6006','jdlw1074@gmail.com','2026-05-14',NULL,9 FROM offices WHERE title='State Representative' AND district=2;
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Republican','Anne Ziegenhorn','anne-ziegenhorn','Wright','WY','82732','P.O. Box 613','307-696-5604','aziegenhorn@yahoo.com','2026-05-22',NULL,9 FROM offices WHERE title='State Representative' AND district=3;
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Republican','Earl Collier','earl-collier','Gillette','WY','82718','7560 Robin Dr','307-696-1519','Earl@collierforwyoming.com','2026-05-15',NULL,9 FROM offices WHERE title='State Representative' AND district=3;
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Republican','Jeremy Haroldson','jeremy-haroldson','Wheatland','WY','82201','96 Reservoir Rd','307-331-2310','jharoldson.impact@hotmail.com','2026-05-18',NULL,9 FROM offices WHERE title='State Representative' AND district=4;
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Republican','Joe Speckner','joe-speckner','Lingle','WY','82223','8602 A State Hwy 157','307-715-0060','Speckner@wyomail.com','2026-05-14',NULL,9 FROM offices WHERE title='State Representative' AND district=5;
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Republican','Karen Weber','karen-weber','Yoder','WY','82244','2398 Road 38','307-338-5011','KARENCWEBER@YAHOO.COM','2026-05-14',NULL,9 FROM offices WHERE title='State Representative' AND district=5;
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Republican','Jim Willox','jim-willox','Douglas','WY','82633','307 E Center','307-351-3242','Jim.Willox@outlook.com','2026-05-14',NULL,10 FROM offices WHERE title='State Representative' AND district=6;
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Republican','Tomi Strock','tomi-strock','Douglas','WY','82633','125 Cherokee Trl','307-359-1120','tomi.strock@gmail.com','2026-05-20',NULL,10 FROM offices WHERE title='State Representative' AND district=6;
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Republican','Bob Nicholas','bob-nicholas','Cheyenne','WY','82009','6225 Mountainview Drive','307-851-7774','bob@proformtech.com','2026-05-18',NULL,10 FROM offices WHERE title='State Representative' AND district=7;
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Republican','Deb Mutter Shamley','deb-mutter-shamley','Cheyenne','WY','82009','7122 Bomar Dr','(307) 630-6508','VoteDebShamleyHD07@gmail.com','2026-05-29',NULL,10 FROM offices WHERE title='State Representative' AND district=7;
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Democratic','Gavin Lobmeyer','gavin-lobmeyer','Cheyenne','WY','82009','500 Sierra Dr','307-228-0154','vote@gavinforwyoming.com','2026-05-28',NULL,10 FROM offices WHERE title='State Representative' AND district=7;
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Republican','Luke Reiner','luke-reiner','Cheyenne','WY','82009','7504 Schrader Ln','307-286-2930','luke@reinerforwyoming.com','2026-05-19',NULL,10 FROM offices WHERE title='State Representative' AND district=8;
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Republican','Steve Johnson','steve-johnson','Cheyenne','WY','82009','11234 Coonrod Rd','307-640-0707','johnsonforhd8@gmail.com','2026-05-14',NULL,10 FROM offices WHERE title='State Representative' AND district=8;
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Democratic','Brenda J Lyttle','brenda-j-lyttle','Cheyenne','WY','82009','700 Samuel Lane','307-432-4029','brenda@lyttlehouse.com','2026-05-19',NULL,10 FROM offices WHERE title='State Representative' AND district=8;
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Republican','Boyd O. Wiggam','boyd-o-wiggam','Cheyenne','WY','82009','2537 Plain View Rd','307-222-9019','bowiggam@gmail.com','2026-05-29',NULL,11 FROM offices WHERE title='State Representative' AND district=9;
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Republican','Exie R. Brown, Jr.','exie-r-brown-jr','Cheyenne','WY','82009','5289 Panorama Dr','307-640-7901','exie@exieforhouse.com','2026-05-14',NULL,11 FROM offices WHERE title='State Representative' AND district=9;
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Democratic','Stephen D. Latham','stephen-d-latham','Cheyenne','WY','82009','4918 Connie Dr','307-274-8309','latham.stephen@yahoo.com','2026-05-15',NULL,11 FROM offices WHERE title='State Representative' AND district=9;
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Republican','Justin Fornstrom','justin-fornstrom','Pine Bluffs','WY','82082','P.O. Box 493','307-630-9131','Fornstromforwy@gmail.com','2026-05-14',NULL,11 FROM offices WHERE title='State Representative' AND district=10;
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Republican','Dan McIntosh','dan-mcintosh','Cheyenne','WY','82003','P.O. Box 9641','307-314-9764','admin@McIntoshforWyoming.com','2026-05-15',NULL,11 FROM offices WHERE title='State Representative' AND district=11;
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Republican','Paul Wing','paul-wing','Cheyenne','WY','82001','1321 W 32nd St','307-222-8614','paul@wingforwyoming.com','2026-05-14',NULL,11 FROM offices WHERE title='State Representative' AND district=11;
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Democratic','Britney Tennant','britney-tennant','Cheyenne','WY','82001','2508 Warren Ave','307-222-8157','campaign@tennantforwyoming.com','2026-05-14',NULL,11 FROM offices WHERE title='State Representative' AND district=11;
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Republican','Clarence Styvar','clarence-styvar','Cheyenne','WY','82007','580 Willson Ct','307-631-2566','clstyvar@wyoming.com','2026-05-14',NULL,11 FROM offices WHERE title='State Representative' AND district=12;
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Republican','Shane Swett','shane-swett','Laramie','WY','82073','P.O. Box 273','307-745-8164','shaneswett3@gmail.com','2026-05-14',NULL,12 FROM offices WHERE title='State Representative' AND district=13;
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Democratic','Ken Chestek','ken-chestek','Laramie','WY','82070','4317 Cliff St','307-460-9139','kchestek@gmail.com','2026-05-14',NULL,12 FROM offices WHERE title='State Representative' AND district=13;
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Republican','Emily Study','emily-study','Laramie','WY','82072','P.O. Box 664','307-310-4471','study4wyoming@gmail.com','2026-05-26',NULL,12 FROM offices WHERE title='State Representative' AND district=14;
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Democratic','Trey Sherwood','trey-sherwood','Laramie','WY','82072','49 North St','307-760-2722','treysherwood@gmail.com','2026-05-14',NULL,12 FROM offices WHERE title='State Representative' AND district=14;
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Republican','Pamela Thayer','pamela-thayer','Rawlins','WY','82301','219 W Maple St','307-321-5624','electthayerwy@gmail.com','2026-05-15',NULL,12 FROM offices WHERE title='State Representative' AND district=15;
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Democratic','Mike Yin','mike-yin','Jackson','WY','83002-3469','P.O. Box 13469','307-201-9897','mike@electmikeyin.com','2026-05-14',NULL,12 FROM offices WHERE title='State Representative' AND district=16;
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Republican','Elizabeth Bingham','elizabeth-bingham','Rock Springs','WY','82901','9 Wardell Ct','307-371-3099','bingham4wyoming@gmail.com','2026-05-14',NULL,12 FROM offices WHERE title='State Representative' AND district=17;
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Democratic','Rah Reinholz','rah-reinholz','Rock Springs','WY','82901','117 1st St','307-212-0841','Wyo.reinholz@gmail.com','2026-05-29',NULL,13 FROM offices WHERE title='State Representative' AND district=17;
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Republican','Kenneth D Roberts','kenneth-d-roberts','Kemmerer','WY','83101','811 Moose St','307-677-3481','kroberts307@outlook.com','2026-05-14',NULL,13 FROM offices WHERE title='State Representative' AND district=18;
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Republican','Scott Heiner','scott-heiner','Green River','WY','82935','P.O. Box 505','307-870-2859','sdheiner9@gmail.com','2026-05-14',NULL,13 FROM offices WHERE title='State Representative' AND district=18;
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Republican','Chad Stephens','chad-stephens','Ft Bridger','WY','82933','3847 County Road 212','307-679-9624','chadstephens72@hotmail.com','2026-05-29',NULL,13 FROM offices WHERE title='State Representative' AND district=19;
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Republican','Joe Webb','joe-webb','Lyman','WY','82937','P.O. Box 1224','307-747-3282','joewebbforhd19@gmail.com','2026-05-28',NULL,13 FROM offices WHERE title='State Representative' AND district=19;
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Republican','Albert Sommers','albert-sommers','Pinedale','WY','82941','P.O. Box 1608','307-360-7060','albert@albertsommers.com','2026-05-14',NULL,13 FROM offices WHERE title='State Representative' AND district=20;
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Republican','Bill Winney','bill-winney','Bondurant','WY','82922','P.O. Box 334','307-413-1506','bill.winney@hotmail.com','2026-05-14',NULL,13 FROM offices WHERE title='State Representative' AND district=20;
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Republican','Matt McGinnis','matt-mcginnis','Pinedale','WY','82941','P.O. Box 1098','307-231-5481','Mcginnisforwyoming@gmail.com','2026-05-21',NULL,13 FROM offices WHERE title='State Representative' AND district=20;
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Republican','McKay L. Erickson','mckay-l-erickson','Afton','WY','83110','2886 Wy241','307-884-6119','ericksonmckay@gmail.com','2026-05-14',NULL,13 FROM offices WHERE title='State Representative' AND district=21;
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Republican','Andrew Byron','andrew-byron','Jackson','WY','83001-4882','P.O. Box 4882','307-690-2767','andrewwyo@gmail.com','2026-05-15',NULL,14 FROM offices WHERE title='State Representative' AND district=22;
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Republican','Shannon A. Brennan','shannon-a-brennan','Jackson','WY','83002','P.O. Box 14550','307-200-9685','sabrennanforwyhouse@gmail.com','2026-05-29',NULL,14 FROM offices WHERE title='State Representative' AND district=23;
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Democratic','Liz Storer','liz-storer','Jackson','WY','83002','P.O. Box 7974','307-421-4711','liz@storerforstatehouse.com','2026-05-20',NULL,14 FROM offices WHERE title='State Representative' AND district=23;
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Republican','Nina Webber','nina-webber','Cody','WY','82414','1108 14th Street Suite 108','307-921-8593','ninawhd24@gmail.com','2026-05-28',NULL,14 FROM offices WHERE title='State Representative' AND district=24;
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Republican','Quin Blair','quin-blair','Cody','WY','82414','P.O. Box 30','307-272-9014','Quin@QuinBlairforWY.com','2026-05-18',NULL,14 FROM offices WHERE title='State Representative' AND district=24;
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Republican','John Wetzel','john-wetzel','Powell','WY','82435','1001 Ponderosa Ct','307-272-0085','wetzelfive@gmail.com','2026-05-14',NULL,14 FROM offices WHERE title='State Representative' AND district=25;
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Republican','Matthew R Legler','matthew-r-legler','Powell','WY','82435','748 Lane 5','307-254-4667','MattLeglerWY@outlook.com','2026-05-17',NULL,14 FROM offices WHERE title='State Representative' AND district=25;
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Republican','Dalton Banks','dalton-banks','Cowley','WY','82420','P.O. Box 64','307-272-7255','daltonpricebanks@gmail.com','2026-05-19',NULL,14 FROM offices WHERE title='State Representative' AND district=26;
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Republican','J. Addison Aagard','j-addison-aagard','Lovell','WY','82431','P.O. Box 293','307-254-3176','Backtothefoundation@outlook.com','2026-05-14',NULL,15 FROM offices WHERE title='State Representative' AND district=26;
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Republican','Martha Lawley','martha-lawley','Worland','WY','82401','818 Sagebrush Dr','307-431-1272','lawleyforwyoming@gmail.com','2026-05-14',NULL,15 FROM offices WHERE title='State Representative' AND district=27;
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Democratic','Theresa Livingston','theresa-livingston','Worland','WY','82401','905 Culbertson Ave','307-529-0860','livingston4wyoming@gmail.com','2026-05-28',NULL,15 FROM offices WHERE title='State Representative' AND district=27;
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Republican','Allen Hogg','allen-hogg','Meeteetse','WY','82433','13 Road 5wt','307-921-0839','allenrhogg@gmail.com','2026-05-15',NULL,15 FROM offices WHERE title='State Representative' AND district=28;
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Republican','Carlin Jones','carlin-jones','Otto','WY','82434','203 1st St S','307-302-0245','cjonesforwyoming@gmail.com','2026-05-20',NULL,15 FROM offices WHERE title='State Representative' AND district=28;
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Republican','Marshall Keller','marshall-keller','Thermopolis','WY','82443','P.O. Box 609','307-921-2744','marshall@kellerforwyo.com','2026-05-14',NULL,15 FROM offices WHERE title='State Representative' AND district=28;
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Republican','Roland Luehne','roland-luehne','Thermopolis','WY','82443','P.O. Box 627','307-921-1776','rluehne@gmail.com','2026-05-28',NULL,15 FROM offices WHERE title='State Representative' AND district=28;
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Republican','James Temple','james-temple','Sheridan','WY','82801','1385 Oxbow Dr','307-210-7066','jtemple4hd29@gmail.com','2026-05-14',NULL,15 FROM offices WHERE title='State Representative' AND district=29;
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Republican','Myca Sturtevant','myca-sturtevant','Sheridan','WY','82801','P.O. Box 21','307-752-6040','mycaforsheridan@gmail.com','2026-05-18',NULL,15 FROM offices WHERE title='State Representative' AND district=29;
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Republican','Noll Roberts','noll-roberts','Sheridan','WY','82801','316 N Jefferson St','307-620-8557','nollroberts@gmail.com','2026-05-29',NULL,16 FROM offices WHERE title='State Representative' AND district=29;
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Republican','Mark Jennings','mark-jennings','Sheridan','WY','82801','765 W Timberline Dr','307-285-6552','Markjenningshd30@yahoo.com','2026-05-15',NULL,16 FROM offices WHERE title='State Representative' AND district=30;
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Republican','Ryan Koltiska','ryan-koltiska','Sheridan','WY','82801','1765 Edwards Dr','307-461-4230','ryan@koltiskaforsheridan.com','2026-05-28',NULL,16 FROM offices WHERE title='State Representative' AND district=30;
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Republican','Douglas Moore','douglas-moore','Gillette','WY','82716','26 Independence Dr','307-689-6892','Dug7088@gmail.com','2026-05-29',NULL,16 FROM offices WHERE title='State Representative' AND district=31;
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Republican','John W. Bear','john-w-bear','Gillette','WY','82718','409 Mills Ave','307-670-1130','jhnbear@gmail.com','2026-05-15',NULL,16 FROM offices WHERE title='State Representative' AND district=31;
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Republican','Ken Clouston','ken-clouston','Gillette','WY','82718','3830 Overdale Dr','307-682-4900','kcc4j@yahoo.com','2026-05-14',NULL,16 FROM offices WHERE title='State Representative' AND district=32;
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Democratic','Ivan D. Posey','ivan-d-posey','Ethete','WY','82520','227 Blue Sky Hwy','307-349-1547','iposey@wyoming.com','2026-05-22',NULL,16 FROM offices WHERE title='State Representative' AND district=33;
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Republican','Pepper L Ottman','pepper-l-ottman','Riverton','WY','82501','P.O. Box 150','307-856-1178','pepper.ottman@wyoleg.gov','2026-05-14',NULL,16 FROM offices WHERE title='State Representative' AND district=34;
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Republican','Christopher Dresang','christopher-dresang','Casper','WY','82609','1640 Nottingham Dr','307-400-8475','natronadresang@gmail.com','2026-05-14',NULL,17 FROM offices WHERE title='State Representative' AND district=35;
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Republican','Tony Locke','tony-locke','Casper','WY','82609','1438 Luker Dr','307-277-9906','TONY@LOCKEFORWYO.COM','2026-05-27',NULL,17 FROM offices WHERE title='State Representative' AND district=35;
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Republican','Art Washut','art-washut','Casper','WY','82609','4031 Crystie Ln','307-251-4725','art.washutforhouse36@gmail.com','2026-05-26',NULL,17 FROM offices WHERE title='State Representative' AND district=36;
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Democratic','Stewart McAdoo','stewart-mcadoo','Casper','WY','82609','3831 Swanton Ave','307-215-5721','mcadoodistrict36@gmail.com','2026-05-25',NULL,17 FROM offices WHERE title='State Representative' AND district=36;
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Republican','Brian Costello','brian-costello','Casper','WY','82604','4165 Ranch Rd','307-797-7437','brian@costelloforcasper.com','2026-05-15',NULL,17 FROM offices WHERE title='State Representative' AND district=37;
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Republican','Donna Rice','donna-rice','Casper','WY','82601','2850 Garden Creek Rd','307-797-8293','donna@votedonnarice.com','2026-05-14',NULL,17 FROM offices WHERE title='State Representative' AND district=37;
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Republican','Ross Schriftman','ross-schriftman','Casper','WY','82604','2200 Mariposa Blvd','307-333-4040','Ross.Schriftman@proton.me','2026-05-14',NULL,17 FROM offices WHERE title='State Representative' AND district=37;
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Democratic','Betsy Erickson','betsy-erickson','Casper','WY','82604','4321 Valley Rd','307-315-8566','ericksonforhd37@yahoo.com','2026-05-14',NULL,17 FROM offices WHERE title='State Representative' AND district=37;
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Republican','Jayme Lien','jayme-lien','Casper','WY','82604','1624 Begonia St','307-267-5675','lienforwy@gmail.com','2026-05-14',NULL,18 FROM offices WHERE title='State Representative' AND district=38;
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Republican','Robert L. Hendry','robert-l-hendry','Lysite','WY','82642','34645 Badwater Rd','307-259-6203','rhendry76@outlook.com','2026-05-28',NULL,18 FROM offices WHERE title='State Representative' AND district=38;
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Democratic','Catherine McQueen','catherine-mcqueen','Casper','WY','82604','6326 Buckboard Rd # 2','307-277-1116','cathymcqueen@bresnan.net','2026-05-29',NULL,18 FROM offices WHERE title='State Representative' AND district=38;
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Republican','Cody Wylie','cody-wylie','Rock Springs','WY','82901','2713 Thunder Gulch Ln','307-371-3283','codywylie@hotmail.com','2026-05-15',NULL,18 FROM offices WHERE title='State Representative' AND district=39;
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Republican','Marilyn Connolly','marilyn-connolly','Buffalo','WY','82834','859 N Desmet Ave','307-217-0345','marelen@vcn.com','2026-05-14',NULL,18 FROM offices WHERE title='State Representative' AND district=40;
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Republican','Mark Jones','mark-jones','Buffalo','WY','82834','P.O. Box 1108','307-620-9297','markjonesforwyoming@gmail.com','2026-05-29',NULL,18 FROM offices WHERE title='State Representative' AND district=40;
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Republican','Erin Edwards','erin-edwards','Cheyenne','WY','82003','P.O. Box 4303','307-220-0754','erinedwardshd41@gmail.com','2026-05-18',NULL,18 FROM offices WHERE title='State Representative' AND district=41;
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Republican','Gary Brown','gary-brown','Cheyenne','WY','82001','1939 1/2 E 18th St','307-369-3453','garybrownforwyoming@gmail.com','2026-05-14',NULL,18 FROM offices WHERE title='State Representative' AND district=41;
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Democratic','Stacy Becker','stacy-becker','Cheyenne','WY','82001','912 W Pershing Blvd','307-287-0850','friskzigg@yahoo.com','2026-05-15',NULL,19 FROM offices WHERE title='State Representative' AND district=41;
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Republican','Rob Geringer','rob-geringer','Cheyenne','WY','82003','P.O. Box 1992','307-617-8995','rob4house@geringerwyo.com','2026-05-14',NULL,19 FROM offices WHERE title='State Representative' AND district=42;
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Democratic','Jim VanDyke','jim-vandyke','Cheyenne','WY','82009','7407 Quarter Circle Dr','307-274-8309','jim@vandyke4wyoming.com','2026-05-15',NULL,19 FROM offices WHERE title='State Representative' AND district=42;
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Republican','Ann Lucas','ann-lucas','Cheyenne','WY','82007','944 Morgan Ranch Rd','307-214-9199','annlucas4wyoming@gmail.com','2026-05-14',NULL,19 FROM offices WHERE title='State Representative' AND district=43;
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Republican','Jessica Crowder','jessica-crowder','Cheyenne','WY','82007','3746 Riata Loop','307-286-4481','jessica@crowderforwyo.com','2026-05-14',NULL,19 FROM offices WHERE title='State Representative' AND district=43;
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Republican','Lee Filer','lee-filer','Cheyenne','WY','82007','1215 Medley Loop','307-421-9554','lee.filer44@gmail.com','2026-05-14',NULL,19 FROM offices WHERE title='State Representative' AND district=44;
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Republican','Ross Davenport','ross-davenport','Laramie','WY','82072','759 N Pine St','970-691-4447','davenport.hd45@gmail.com','2026-05-29',NULL,19 FROM offices WHERE title='State Representative' AND district=45;
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Democratic','Karlee Provenza','karlee-provenza','Laramie','WY','82073','P.O. Box 1715','307-977-0202','karleerprovenza@gmail.com','2026-05-18',NULL,20 FROM offices WHERE title='State Representative' AND district=45;
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Republican','Cam Wright','cam-wright','Laramie','WY','82070','35 Walgren Lane','307-223-5686','cam4wy@gmail.com','2026-05-14',NULL,20 FROM offices WHERE title='State Representative' AND district=46;
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Republican','Ocean Andrew','ocean-andrew','Laramie','WY','82073','P.O. Box 2148','307-314-9246','contact@oceanandrew.com','2026-05-14',NULL,20 FROM offices WHERE title='State Representative' AND district=46;
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Democratic','Gary Wilken','gary-wilken','Laramie','WY','82073','P.O. Box 932','307-760-0732','info@garywilkenhd46.com','2026-05-14',NULL,20 FROM offices WHERE title='State Representative' AND district=46;
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Republican','Eamon O''Toole','eamon-otoole','Baggs','WY','82321','Box 218','307-361-8030','eamon.otooleranch@gmail.com','2026-05-14',NULL,20 FROM offices WHERE title='State Representative' AND district=47;
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Republican','Darin McCann','darin-mccann','Rock Springs','WY','82901','532 Quadrant Dr.','307-899-2270','mccann4wyhd48@gmail.com','2026-05-25',NULL,20 FROM offices WHERE title='State Representative' AND district=48;
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Republican','James Wamsley','james-wamsley','Rock Springs','WY','82901','524 Winterhawk Dr','307-389-2309','james@jameswamsleyforwyoming.com','2026-05-15',NULL,20 FROM offices WHERE title='State Representative' AND district=48;
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Republican','David Walton','david-walton','Evanston','WY','82930','216 Wood Ridge Ln','307-679-6430','dkw2raw@Myctl.net','2026-05-19',NULL,20 FROM offices WHERE title='State Representative' AND district=49;
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Republican','Robert Wharff','robert-wharff','Evanston','WY','82930','137 Shady Lane','307-799-8944','rawharff@gmail.com','2026-05-19',NULL,21 FROM offices WHERE title='State Representative' AND district=49;
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Republican','David Hill','david-hill','Cody','WY','82414','2401 Heights Ave','307-527-0944','David@hill4wyo.com','2026-05-14',NULL,21 FROM offices WHERE title='State Representative' AND district=50;
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Republican','Levi Asay','levi-asay','Cody','WY','82414','1535 Bleistein Ave','307-272-7297','levi@asayforwyoming.com','2026-05-28',NULL,21 FROM offices WHERE title='State Representative' AND district=50;
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Republican','Laurie Bratten','laurie-bratten','Sheridan','WY','82801','1004 Big Goose Rd','307-683-1788','LaurieForWyoming@ProtonMail.com','2026-05-14',NULL,21 FROM offices WHERE title='State Representative' AND district=51;
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Republican','Susan Bigelow','susan-bigelow','Sheridan','WY','82801','1584 S Mountain View Dr','307-752-1762','susan@bigelowforhd51.com','2026-05-14',NULL,21 FROM offices WHERE title='State Representative' AND district=51;
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Republican','Bill Fortner','bill-fortner','Gillette','WY','82717-1013','P.O. Box 1013','307-660-8563','brfortner@vcn.com','2026-05-14',NULL,21 FROM offices WHERE title='State Representative' AND district=52;
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Republican','Ronda Boller','ronda-boller','Gillette','WY','82716','103 Pineview Dr','307-660-2895','votebollerhd52@gmail.com','2026-05-18',NULL,21 FROM offices WHERE title='State Representative' AND district=52;
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Republican','Christopher R Knapp','christopher-r-knapp','Gillette','WY','82716','1134 E 12th St','307-660-4566','copychris@vcn.com','2026-05-21',NULL,21 FROM offices WHERE title='State Representative' AND district=53;
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Republican','Greg Schreurs','greg-schreurs','Gillette','WY','82717','P.O. Box 2187','307-686-8270','GSchreurs1@gmail.com','2026-05-15',NULL,21 FROM offices WHERE title='State Representative' AND district=53;
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Republican','Jeff Martin','jeff-martin','Lander','WY','82520','15 Gale Dr','307-714-0014','jmartinforhouse54@gmail.com','2026-05-28',NULL,22 FROM offices WHERE title='State Representative' AND district=54;
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Republican','Lloyd Charles Larsen','lloyd-charles-larsen','Lander','WY','82520','1076 S 2nd St','307-321-1221','lloydlarsen2020@gmail.com','2026-05-14',NULL,22 FROM offices WHERE title='State Representative' AND district=54;
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Republican','Carl Manning','carl-manning','Riverton','WY','82501','326 Moose Dr','307-851-3440','manningfor55@gmail.com','2026-05-14',NULL,22 FROM offices WHERE title='State Representative' AND district=55;
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Republican','Elissa Campbell','elissa-campbell','Casper','WY','82601','718 Divine Ave','307-439-5364','elissa@campbell4wyoming.com','2026-05-15',NULL,22 FROM offices WHERE title='State Representative' AND district=56;
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Republican','Pete Fox','pete-fox','Casper','WY','82601','6211 S Walnut St','832-561-6050','foxpb2@proton.me','2026-05-27',NULL,22 FROM offices WHERE title='State Representative' AND district=56;
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Republican','Jeanette Ward','jeanette-ward','Casper','WY','82609','1600 E 26th St','307-222-9747','jwforw@gmail.com','2026-05-18',NULL,22 FROM offices WHERE title='State Representative' AND district=57;
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Republican','Julie Jarvis','julie-jarvis','Casper','WY','82601','P.O. Box 511','307-670-0202','Julie@jarviswyo.com','2026-05-18',NULL,22 FROM offices WHERE title='State Representative' AND district=57;
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Democratic','Luc Colgrove','luc-colgrove','Casper','WY','82609','1420 Missouri Ave # 8','307-222-8006','Hd57@lucascolgrove.com','2026-05-29',NULL,22 FROM offices WHERE title='State Representative' AND district=57;
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Republican','Bill Allemand','bill-allemand','Midwest','WY','82643','P.O. Box 119','307-277-0902','billshot307@gmail.com','2026-05-14',NULL,23 FROM offices WHERE title='State Representative' AND district=58;
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Republican','Peter Boyer','peter-boyer','Bar Nunn','WY','82601','2116 Omaha Trl','307-301-8102','peterboyerhd58@gmail.com','2026-05-14',NULL,23 FROM offices WHERE title='State Representative' AND district=58;
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Democratic','Keenan Morgan','keenan-morgan','Bar Nunn','WY','82601','2340 Lakota Trl','307-262-2002','k.morgan.44307@gmail.com','2026-05-20',NULL,23 FROM offices WHERE title='State Representative' AND district=58;
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Republican','J.R. Riggins','jr-riggins','Casper','WY','82604','1872 Jim Bridger Ave','307-262-8446','jr.riggins@jrforhouse.com','2026-05-18',NULL,23 FROM offices WHERE title='State Representative' AND district=59;
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Republican','Neil Jeske','neil-jeske','Casper','WY','82604','1210 S Willow St # 2','307-258-3012','neil4wyo@pm.me','2026-05-14',NULL,23 FROM offices WHERE title='State Representative' AND district=59;
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Democratic','Laurie Longtine','laurie-longtine','Casper','WY','82604','4320 Cy Avenue','307-259-1841','ledgerpluscasper@gmail.com','2026-05-29',NULL,23 FROM offices WHERE title='State Representative' AND district=59;
-- HD60: source city field was '82935' (zip code); corrected to 'Green River'
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Republican','Marlene Brady','marlene-brady','Green River','WY','82935','P.O. Box 643','307-871-4583','marlenebradyforhd60@gmail.com','2026-05-14',NULL,23 FROM offices WHERE title='State Representative' AND district=60;
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Republican','Tony Niemiec','tony-niemiec','Green River','WY','82935','505 Wind River Dr Apt A','307-871-1730','tonyniemiechousedistrict60@gmail.com','2026-05-14',NULL,23 FROM offices WHERE title='State Representative' AND district=60;
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Republican','Andrew Server','andrew-server','Cheyenne','WY','82001','2005 Appaloosa Dr','307-222-3251','serverforwy@gmail.com','2026-05-19',NULL,24 FROM offices WHERE title='State Representative' AND district=61;
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Republican','Seth Bard','seth-bard','Cheyenne','WY','82001','4720 Long Branch Loop','307-222-8384','BardForHouse@gmail.com','2026-05-28',NULL,24 FROM offices WHERE title='State Representative' AND district=61;
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Democratic','Kristen-Erin Balderaz','kristen-erin-balderaz','Cheyenne','WY','82001','4524 E 16th St','307-275-4412','kristenerin.balderaz@gmail.com','2026-05-15',NULL,24 FROM offices WHERE title='State Representative' AND district=61;
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Republican','Edis Allen','edis-allen','Glenrock','WY','82637','301 S 4 Th St','307-258-9608','Edissix@gmail.com','2026-05-14',NULL,24 FROM offices WHERE title='State Representative' AND district=62;
INSERT OR IGNORE INTO candidates (office_id,party,full_name,slug,city,state,zip,mailing_address,phone,email,filed_at,withdrawn_at,source_page) SELECT id,'Republican','Kevin J. Campbell','kevin-j-campbell','Glenrock','WY','82637','P.O. Box 83','307-267-2038','kevin.highcountry@gmail.com','2026-05-27',NULL,24 FROM offices WHERE title='State Representative' AND district=62;
