-- Generated from Candidates/data/rubrics/wy-primary-2026-v1.md
-- Do not edit this file directly.

INSERT OR IGNORE INTO guide_rubric_versions
  (rubric_key, title, election_cycle, score_min, score_max, unknown_policy, status, source_sha256, activated_at)
VALUES ('wy-primary-2026-v1', 'Wyoming 2026 Primary Candidate Rubric', '2026-primary', 0, 5, 'excluded', 'active', 'cbf458344636d5e8df23805ca2b802a5376ff324695f32e3131fa121859f5994', datetime('now'));

INSERT OR IGNORE INTO guide_rubric_categories
  (rubric_version_id, category_key, label, description, evidence_guidance, weight, display_order)
SELECT id, 'constitutional_oath', 'Constitutional oath and rule of law', 'Evaluate respect for constitutional limits, the oath of office, due process, and the lawful roles of the legislative, executive, and judicial branches. Distinguish disagreement with a ruling from documented attempts to evade controlling law or the constitutional amendment process.', 'Prefer constitutional text, court records, enacted legislation, recorded votes, official statements, and direct candidate explanations. Do not infer intent from party membership or association alone.', 15, 10 FROM guide_rubric_versions WHERE rubric_key = 'wy-primary-2026-v1';

INSERT OR IGNORE INTO guide_rubric_categories
  (rubric_version_id, category_key, label, description, evidence_guidance, weight, display_order)
SELECT id, 'character', 'Character, honesty, and courage', 'Evaluate documented truthfulness, consistency between statements and conduct, willingness to correct errors, treatment of others, and willingness to take accountable public positions under pressure.', 'Use attributable public conduct, corrections, official findings, direct statements, and corroborated reporting. Do not score rumor, anonymous accusation, or disagreement over policy as a character defect.', 15, 20 FROM guide_rubric_versions WHERE rubric_key = 'wy-primary-2026-v1';

INSERT OR IGNORE INTO guide_rubric_categories
  (rubric_version_id, category_key, label, description, evidence_guidance, weight, display_order)
SELECT id, 'competence', 'Competence and readiness', 'Evaluate demonstrated understanding of the office, relevant responsibilities, preparation, judgment, and the ability to explain how proposed actions could be lawfully and practically carried out.', 'Consider relevant work, public service, legislative or administrative performance, debates, detailed proposals, and direct answers. Do not require prior elected office.', 10, 30 FROM guide_rubric_versions WHERE rubric_key = 'wy-primary-2026-v1';

INSERT OR IGNORE INTO guide_rubric_categories
  (rubric_version_id, category_key, label, description, evidence_guidance, weight, display_order)
SELECT id, 'accountability', 'Accountability and transparency', 'Evaluate disclosure, responsiveness, explanation of decisions, compliance with reporting duties, correction of material errors, and willingness to provide voters with verifiable information.', 'Prefer required filings, public records, correction history, direct responses, meeting records, and documented patterns of disclosure or nondisclosure.', 10, 40 FROM guide_rubric_versions WHERE rubric_key = 'wy-primary-2026-v1';

INSERT OR IGNORE INTO guide_rubric_categories
  (rubric_version_id, category_key, label, description, evidence_guidance, weight, display_order)
SELECT id, 'fiscal', 'Fiscal responsibility', 'Evaluate whether the candidate''s record and proposals identify costs, funding sources, tradeoffs, long-term obligations, and responsible stewardship of public money.', 'Use budgets, fiscal notes, recorded votes, campaign finance filings, audits, detailed proposals, and direct explanations. Do not treat wealth, poverty, or a disclosed contribution as proof of fiscal character.', 10, 50 FROM guide_rubric_versions WHERE rubric_key = 'wy-primary-2026-v1';

INSERT OR IGNORE INTO guide_rubric_categories
  (rubric_version_id, category_key, label, description, evidence_guidance, weight, display_order)
SELECT id, 'local_impact', 'Local impact and Wyoming fit', 'Evaluate understanding of Wyoming communities, constitutional and jurisdictional boundaries, and the likely local effects of the candidate''s record or proposals on land, water, energy, agriculture, families, and local government.', 'Prefer Wyoming-specific proposals, local records, public meetings, constituent work, impact analysis, and direct explanations rather than national talking points alone.', 10, 60 FROM guide_rubric_versions WHERE rubric_key = 'wy-primary-2026-v1';

INSERT OR IGNORE INTO guide_rubric_categories
  (rubric_version_id, category_key, label, description, evidence_guidance, weight, display_order)
SELECT id, 'public_service', 'Public service over self-interest', 'Evaluate documented service, stewardship, conflicts management, use of public responsibility, and whether conduct demonstrates attention to constituents and public obligations rather than personal benefit alone.', 'Use service records, ethics disclosures, conflict documentation, constituent work, official findings, and corroborated conduct. A disclosed interest is not misconduct by itself.', 10, 70 FROM guide_rubric_versions WHERE rubric_key = 'wy-primary-2026-v1';

INSERT OR IGNORE INTO guide_rubric_categories
  (rubric_version_id, category_key, label, description, evidence_guidance, weight, display_order)
SELECT id, 'issue_alignment', 'Issue alignment with Skovgard 2026', 'Compare the candidate''s documented positions and record with Jimmy Skovgard''s published platform priorities. This category is explicitly perspective-specific and must not be presented as a neutral measure of candidate quality.', 'Use current published platforms, direct statements, recorded votes, and detailed proposals. Mark changed or unclear positions and do not infer alignment where no evidence exists.', 10, 80 FROM guide_rubric_versions WHERE rubric_key = 'wy-primary-2026-v1';

INSERT OR IGNORE INTO guide_rubric_categories
  (rubric_version_id, category_key, label, description, evidence_guidance, weight, display_order)
SELECT id, 'coalition', 'Coalition-building and temperament', 'Evaluate demonstrated ability to work through disagreement, communicate responsibly, build effective support, and maintain principled but functional relationships required by the office.', 'Use legislative or organizational outcomes, public forums, direct working relationships, attributable conduct, and corroborated reporting. Style alone is not evidence of effectiveness or failure.', 5, 90 FROM guide_rubric_versions WHERE rubric_key = 'wy-primary-2026-v1';

INSERT OR IGNORE INTO guide_rubric_categories
  (rubric_version_id, category_key, label, description, evidence_guidance, weight, display_order)
SELECT id, 'evidence_quality', 'Evidence quality', 'Evaluate the authority, freshness, completeness, independence, and corroboration of the evidence available for the candidate. This category describes the research record, not the candidate''s ideology.', 'Higher scores require multiple fresh, direct, authoritative sources. Sparse, stale, indirect, or internally conflicting evidence lowers this score and must also be disclosed through evidence coverage.', 5, 100 FROM guide_rubric_versions WHERE rubric_key = 'wy-primary-2026-v1';

