-- Title-based precinct_code backfill for local D1 (county+title WHERE clause, no IDs).
-- Applies parsePrecinctCode() logic from infer_precinct_committee_offices.mjs.
-- Includes Platte-specific pattern: 'Platte N-N ...' format.

UPDATE offices SET precinct_code = '01' WHERE LOWER(county) = 'big horn' AND title = 'Basin-01 Precinct Precinct Committeeman (Republican) (M)' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '01' WHERE LOWER(county) = 'big horn' AND title = 'Basin-01 Precinct Precinct Committeewoman (Republican) (F)' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '02' WHERE LOWER(county) = 'big horn' AND title = 'Burlington-02 Precinct Precinct Committeeman (Republican) (M)' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '02' WHERE LOWER(county) = 'big horn' AND title = 'Burlington-02 Precinct Precinct Committeewoman (Republican) (F)' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '05' WHERE LOWER(county) = 'big horn' AND title = 'Emblem-05 Precinct Precinct Committeeman (Republican) (M)' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '05' WHERE LOWER(county) = 'big horn' AND title = 'Emblem-05 Precinct Precinct Committeewoman (Republican) (F)' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '06' WHERE LOWER(county) = 'big horn' AND title = 'Hyattville-06 Precinct Precinct Committeeman (Republican) (M)' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '03' WHERE LOWER(county) = 'big horn' AND title = 'Otto-03 Precinct Precinct Committeeman (Republican) (M)' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '03' WHERE LOWER(county) = 'big horn' AND title = 'Otto-03 Precinct Precinct Committeewoman (Republican) (F)' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '01-01' WHERE LOWER(county) = 'campbell' AND title = 'Campbell Precinct 01-01 Precinct Committeeman (Democratic) (M)' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '01-01' WHERE LOWER(county) = 'campbell' AND title = 'Campbell Precinct 01-01 Precinct Committeewoman (Democratic) (F)' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '01-02' WHERE LOWER(county) = 'campbell' AND title = 'Campbell Precinct 01-02 Precinct Committeeman (Democratic) (M)' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '01-02' WHERE LOWER(county) = 'campbell' AND title = 'Campbell Precinct 01-02 Precinct Committeewoman (Democratic) (F)' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '01-03' WHERE LOWER(county) = 'campbell' AND title = 'Campbell Precinct 01-03 Precinct Committeeman (Democratic) (M)' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '01-03' WHERE LOWER(county) = 'campbell' AND title = 'Campbell Precinct 01-03 Precinct Committeewoman (Democratic) (F)' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '01-05' WHERE LOWER(county) = 'campbell' AND title = 'Campbell Precinct 01-05 Precinct Committeeman (Democratic) (M)' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '01-05' WHERE LOWER(county) = 'campbell' AND title = 'Campbell Precinct 01-05 Precinct Committeewoman (Democratic) (F)' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '01-05' WHERE LOWER(county) = 'campbell' AND title = 'Campbell Precinct 01-05 Precinct Committeewoman (Republican) (F)' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '01-07' WHERE LOWER(county) = 'campbell' AND title = 'Campbell Precinct 01-07 Precinct Committeeman (Democratic) (M)' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '01-07' WHERE LOWER(county) = 'campbell' AND title = 'Campbell Precinct 01-07 Precinct Committeeman (Republican) (M)' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '01-07' WHERE LOWER(county) = 'campbell' AND title = 'Campbell Precinct 01-07 Precinct Committeewoman (Democratic) (F)' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '01-07' WHERE LOWER(county) = 'campbell' AND title = 'Campbell Precinct 01-07 Precinct Committeewoman (Republican) (F)' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '01-09' WHERE LOWER(county) = 'campbell' AND title = 'Campbell Precinct 01-09 Precinct Committeeman (Democratic) (M)' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '01-09' WHERE LOWER(county) = 'campbell' AND title = 'Campbell Precinct 01-09 Precinct Committeeman (Republican) (M)' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '01-09' WHERE LOWER(county) = 'campbell' AND title = 'Campbell Precinct 01-09 Precinct Committeewoman (Democratic) (F)' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '01-09' WHERE LOWER(county) = 'campbell' AND title = 'Campbell Precinct 01-09 Precinct Committeewoman (Republican) (F)' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '01-12' WHERE LOWER(county) = 'campbell' AND title = 'Campbell Precinct 01-12 Precinct Committeeman (Democratic) (M)' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '01-12' WHERE LOWER(county) = 'campbell' AND title = 'Campbell Precinct 01-12 Precinct Committeewoman (Democratic) (F)' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '01-12' WHERE LOWER(county) = 'campbell' AND title = 'Campbell Precinct 01-12 Precinct Committeewoman (Republican) (F)' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '01-14' WHERE LOWER(county) = 'campbell' AND title = 'Campbell Precinct 01-14 Precinct Committeeman (Democratic) (M)' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '01-14' WHERE LOWER(county) = 'campbell' AND title = 'Campbell Precinct 01-14 Precinct Committeeman (Republican) (M)' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '01-14' WHERE LOWER(county) = 'campbell' AND title = 'Campbell Precinct 01-14 Precinct Committeewoman (Democratic) (F)' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '01-14' WHERE LOWER(county) = 'campbell' AND title = 'Campbell Precinct 01-14 Precinct Committeewoman (Republican) (F)' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '01-15' WHERE LOWER(county) = 'campbell' AND title = 'Campbell Precinct 01-15 Precinct Committeeman (Democratic) (M)' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '01-15' WHERE LOWER(county) = 'campbell' AND title = 'Campbell Precinct 01-15 Precinct Committeeman (Republican) (M)' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '01-15' WHERE LOWER(county) = 'campbell' AND title = 'Campbell Precinct 01-15 Precinct Committeewoman (Democratic) (F)' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '01-15' WHERE LOWER(county) = 'campbell' AND title = 'Campbell Precinct 01-15 Precinct Committeewoman (Republican) (F)' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '01-16' WHERE LOWER(county) = 'campbell' AND title = 'Campbell Precinct 01-16 Precinct Committeeman (Democratic) (M)' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '01-16' WHERE LOWER(county) = 'campbell' AND title = 'Campbell Precinct 01-16 Precinct Committeeman (Republican) (M)' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '01-16' WHERE LOWER(county) = 'campbell' AND title = 'Campbell Precinct 01-16 Precinct Committeewoman (Democratic) (F)' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '01-16' WHERE LOWER(county) = 'campbell' AND title = 'Campbell Precinct 01-16 Precinct Committeewoman (Republican) (F)' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '01-17' WHERE LOWER(county) = 'campbell' AND title = 'Campbell Precinct 01-17 Precinct Committeeman (Democratic) (M)' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '01-17' WHERE LOWER(county) = 'campbell' AND title = 'Campbell Precinct 01-17 Precinct Committeeman (Republican) (M)' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '01-17' WHERE LOWER(county) = 'campbell' AND title = 'Campbell Precinct 01-17 Precinct Committeewoman (Democratic) (F)' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '01-17' WHERE LOWER(county) = 'campbell' AND title = 'Campbell Precinct 01-17 Precinct Committeewoman (Republican) (F)' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '01-18' WHERE LOWER(county) = 'campbell' AND title = 'Campbell Precinct 01-18 Precinct Committeeman (Democratic) (M)' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '01-18' WHERE LOWER(county) = 'campbell' AND title = 'Campbell Precinct 01-18 Precinct Committeeman (Republican) (M)' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '01-18' WHERE LOWER(county) = 'campbell' AND title = 'Campbell Precinct 01-18 Precinct Committeewoman (Democratic) (F)' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '01-18' WHERE LOWER(county) = 'campbell' AND title = 'Campbell Precinct 01-18 Precinct Committeewoman (Republican) (F)' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '01-19' WHERE LOWER(county) = 'campbell' AND title = 'Campbell Precinct 01-19 Precinct Committeeman (Democratic) (M)' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '01-19' WHERE LOWER(county) = 'campbell' AND title = 'Campbell Precinct 01-19 Precinct Committeeman (Republican) (M)' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '01-19' WHERE LOWER(county) = 'campbell' AND title = 'Campbell Precinct 01-19 Precinct Committeewoman (Democratic) (F)' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '01-19' WHERE LOWER(county) = 'campbell' AND title = 'Campbell Precinct 01-19 Precinct Committeewoman (Republican) (F)' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '01-20' WHERE LOWER(county) = 'campbell' AND title = 'Campbell Precinct 01-20 Precinct Committeeman (Democratic) (M)' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '01-20' WHERE LOWER(county) = 'campbell' AND title = 'Campbell Precinct 01-20 Precinct Committeeman (Republican) (M)' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '01-20' WHERE LOWER(county) = 'campbell' AND title = 'Campbell Precinct 01-20 Precinct Committeewoman (Democratic) (F)' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '01-20' WHERE LOWER(county) = 'campbell' AND title = 'Campbell Precinct 01-20 Precinct Committeewoman (Republican) (F)' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '01-21' WHERE LOWER(county) = 'campbell' AND title = 'Campbell Precinct 01-21 Precinct Committeeman (Democratic) (M)' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '01-21' WHERE LOWER(county) = 'campbell' AND title = 'Campbell Precinct 01-21 Precinct Committeeman (Republican) (M)' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '01-21' WHERE LOWER(county) = 'campbell' AND title = 'Campbell Precinct 01-21 Precinct Committeewoman (Democratic) (F)' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '01-21' WHERE LOWER(county) = 'campbell' AND title = 'Campbell Precinct 01-21 Precinct Committeewoman (Republican) (F)' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '01-22' WHERE LOWER(county) = 'campbell' AND title = 'Campbell Precinct 01-22 Precinct Committeeman (Democratic) (M)' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '01-22' WHERE LOWER(county) = 'campbell' AND title = 'Campbell Precinct 01-22 Precinct Committeeman (Republican) (M)' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '01-22' WHERE LOWER(county) = 'campbell' AND title = 'Campbell Precinct 01-22 Precinct Committeewoman (Democratic) (F)' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '01-22' WHERE LOWER(county) = 'campbell' AND title = 'Campbell Precinct 01-22 Precinct Committeewoman (Republican) (F)' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '01-23' WHERE LOWER(county) = 'campbell' AND title = 'Campbell Precinct 01-23 Precinct Committeeman (Democratic) (M)' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '01-23' WHERE LOWER(county) = 'campbell' AND title = 'Campbell Precinct 01-23 Precinct Committeeman (Republican) (M)' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '01-23' WHERE LOWER(county) = 'campbell' AND title = 'Campbell Precinct 01-23 Precinct Committeewoman (Democratic) (F)' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '01-23' WHERE LOWER(county) = 'campbell' AND title = 'Campbell Precinct 01-23 Precinct Committeewoman (Republican) (F)' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '01-24' WHERE LOWER(county) = 'campbell' AND title = 'Campbell Precinct 01-24 Precinct Committeeman (Democratic) (M)' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '01-24' WHERE LOWER(county) = 'campbell' AND title = 'Campbell Precinct 01-24 Precinct Committeeman (Republican) (M)' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '01-24' WHERE LOWER(county) = 'campbell' AND title = 'Campbell Precinct 01-24 Precinct Committeewoman (Democratic) (F)' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '01-24' WHERE LOWER(county) = 'campbell' AND title = 'Campbell Precinct 01-24 Precinct Committeewoman (Republican) (F)' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '01-25' WHERE LOWER(county) = 'campbell' AND title = 'Campbell Precinct 01-25 Precinct Committeeman (Democratic) (M)' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '01-25' WHERE LOWER(county) = 'campbell' AND title = 'Campbell Precinct 01-25 Precinct Committeeman (Republican) (M)' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '01-25' WHERE LOWER(county) = 'campbell' AND title = 'Campbell Precinct 01-25 Precinct Committeewoman (Democratic) (F)' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '01-25' WHERE LOWER(county) = 'campbell' AND title = 'Campbell Precinct 01-25 Precinct Committeewoman (Republican) (F)' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '01-26' WHERE LOWER(county) = 'campbell' AND title = 'Campbell Precinct 01-26 Precinct Committeeman (Democratic) (M)' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '01-26' WHERE LOWER(county) = 'campbell' AND title = 'Campbell Precinct 01-26 Precinct Committeeman (Republican) (M)' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '01-26' WHERE LOWER(county) = 'campbell' AND title = 'Campbell Precinct 01-26 Precinct Committeewoman (Democratic) (F)' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '01-26' WHERE LOWER(county) = 'campbell' AND title = 'Campbell Precinct 01-26 Precinct Committeewoman (Republican) (F)' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '01-27' WHERE LOWER(county) = 'campbell' AND title = 'Campbell Precinct 01-27 Precinct Committeeman (Democratic) (M)' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '01-27' WHERE LOWER(county) = 'campbell' AND title = 'Campbell Precinct 01-27 Precinct Committeeman (Republican) (M)' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '01-27' WHERE LOWER(county) = 'campbell' AND title = 'Campbell Precinct 01-27 Precinct Committeewoman (Democratic) (F)' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '01-27' WHERE LOWER(county) = 'campbell' AND title = 'Campbell Precinct 01-27 Precinct Committeewoman (Republican) (F)' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '02-01' WHERE LOWER(county) = 'campbell' AND title = 'Campbell Precinct 02-01 Precinct Committeeman (Democratic) (M)' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '02-01' WHERE LOWER(county) = 'campbell' AND title = 'Campbell Precinct 02-01 Precinct Committeeman (Republican) (M)' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '02-01' WHERE LOWER(county) = 'campbell' AND title = 'Campbell Precinct 02-01 Precinct Committeewoman (Democratic) (F)' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '02-01' WHERE LOWER(county) = 'campbell' AND title = 'Campbell Precinct 02-01 Precinct Committeewoman (Republican) (F)' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '03-01' WHERE LOWER(county) = 'campbell' AND title = 'Campbell Precinct 03-01 Precinct Committeeman (Democratic) (M)' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '03-01' WHERE LOWER(county) = 'campbell' AND title = 'Campbell Precinct 03-01 Precinct Committeeman (Republican) (M)' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '03-01' WHERE LOWER(county) = 'campbell' AND title = 'Campbell Precinct 03-01 Precinct Committeewoman (Democratic) (F)' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '03-01' WHERE LOWER(county) = 'campbell' AND title = 'Campbell Precinct 03-01 Precinct Committeewoman (Republican) (F)' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '04-01' WHERE LOWER(county) = 'campbell' AND title = 'Campbell Precinct 04-01 Precinct Committeeman (Democratic) (M)' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '04-01' WHERE LOWER(county) = 'campbell' AND title = 'Campbell Precinct 04-01 Precinct Committeeman (Republican) (M)' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '04-01' WHERE LOWER(county) = 'campbell' AND title = 'Campbell Precinct 04-01 Precinct Committeewoman (Democratic) (F)' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '04-01' WHERE LOWER(county) = 'campbell' AND title = 'Campbell Precinct 04-01 Precinct Committeewoman (Republican) (F)' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '06-01' WHERE LOWER(county) = 'campbell' AND title = 'Campbell Precinct 06-01 Precinct Committeeman (Democratic) (M)' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '06-01' WHERE LOWER(county) = 'campbell' AND title = 'Campbell Precinct 06-01 Precinct Committeeman (Republican) (M)' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '06-01' WHERE LOWER(county) = 'campbell' AND title = 'Campbell Precinct 06-01 Precinct Committeewoman (Democratic) (F)' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '06-01' WHERE LOWER(county) = 'campbell' AND title = 'Campbell Precinct 06-01 Precinct Committeewoman (Republican) (F)' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '07-01' WHERE LOWER(county) = 'campbell' AND title = 'Campbell Precinct 07-01 Precinct Committeeman (Democratic) (M)' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '07-01' WHERE LOWER(county) = 'campbell' AND title = 'Campbell Precinct 07-01 Precinct Committeeman (Republican) (M)' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '07-01' WHERE LOWER(county) = 'campbell' AND title = 'Campbell Precinct 07-01 Precinct Committeewoman (Democratic) (F)' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '07-01' WHERE LOWER(county) = 'campbell' AND title = 'Campbell Precinct 07-01 Precinct Committeewoman (Republican) (F)' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '08-01' WHERE LOWER(county) = 'campbell' AND title = 'Campbell Precinct 08-01 Precinct Committeeman (Democratic) (M)' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '08-01' WHERE LOWER(county) = 'campbell' AND title = 'Campbell Precinct 08-01 Precinct Committeeman (Republican) (M)' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '08-01' WHERE LOWER(county) = 'campbell' AND title = 'Campbell Precinct 08-01 Precinct Committeewoman (Democratic) (F)' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '08-01' WHERE LOWER(county) = 'campbell' AND title = 'Campbell Precinct 08-01 Precinct Committeewoman (Republican) (F)' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '09-01' WHERE LOWER(county) = 'campbell' AND title = 'Campbell Precinct 09-01 Precinct Committeeman (Democratic) (M)' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '09-01' WHERE LOWER(county) = 'campbell' AND title = 'Campbell Precinct 09-01 Precinct Committeeman (Republican) (M)' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '09-01' WHERE LOWER(county) = 'campbell' AND title = 'Campbell Precinct 09-01 Precinct Committeewoman (Democratic) (F)' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '09-01' WHERE LOWER(county) = 'campbell' AND title = 'Campbell Precinct 09-01 Precinct Committeewoman (Republican) (F)' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '13-01' WHERE LOWER(county) = 'campbell' AND title = 'Campbell Precinct 13-01 Precinct Committeeman (Democratic) (M)' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '13-01' WHERE LOWER(county) = 'campbell' AND title = 'Campbell Precinct 13-01 Precinct Committeeman (Republican) (M)' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '13-01' WHERE LOWER(county) = 'campbell' AND title = 'Campbell Precinct 13-01 Precinct Committeewoman (Democratic) (F)' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '13-01' WHERE LOWER(county) = 'campbell' AND title = 'Campbell Precinct 13-01 Precinct Committeewoman (Republican) (F)' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '14-01' WHERE LOWER(county) = 'campbell' AND title = 'Campbell Precinct 14-01 Precinct Committeeman (Democratic) (M)' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '14-01' WHERE LOWER(county) = 'campbell' AND title = 'Campbell Precinct 14-01 Precinct Committeeman (Republican) (M)' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '14-01' WHERE LOWER(county) = 'campbell' AND title = 'Campbell Precinct 14-01 Precinct Committeewoman (Democratic) (F)' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '14-01' WHERE LOWER(county) = 'campbell' AND title = 'Campbell Precinct 14-01 Precinct Committeewoman (Republican) (F)' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '14-02' WHERE LOWER(county) = 'campbell' AND title = 'Campbell Precinct 14-02 Precinct Committeeman (Democratic) (M)' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '14-02' WHERE LOWER(county) = 'campbell' AND title = 'Campbell Precinct 14-02 Precinct Committeeman (Republican) (M)' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '14-02' WHERE LOWER(county) = 'campbell' AND title = 'Campbell Precinct 14-02 Precinct Committeewoman (Democratic) (F)' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '14-02' WHERE LOWER(county) = 'campbell' AND title = 'Campbell Precinct 14-02 Precinct Committeewoman (Republican) (F)' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '18-01' WHERE LOWER(county) = 'campbell' AND title = 'Campbell Precinct 18-01 Precinct Committeeman (Democratic) (M)' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '18-01' WHERE LOWER(county) = 'campbell' AND title = 'Campbell Precinct 18-01 Precinct Committeeman (Republican) (M)' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '18-01' WHERE LOWER(county) = 'campbell' AND title = 'Campbell Precinct 18-01 Precinct Committeewoman (Democratic) (F)' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '18-01' WHERE LOWER(county) = 'campbell' AND title = 'Campbell Precinct 18-01 Precinct Committeewoman (Republican) (F)' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '19-01' WHERE LOWER(county) = 'campbell' AND title = 'Campbell Precinct 19-01 Precinct Committeeman (Democratic) (M)' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '19-01' WHERE LOWER(county) = 'campbell' AND title = 'Campbell Precinct 19-01 Precinct Committeeman (Republican) (M)' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '19-01' WHERE LOWER(county) = 'campbell' AND title = 'Campbell Precinct 19-01 Precinct Committeewoman (Democratic) (F)' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '19-01' WHERE LOWER(county) = 'campbell' AND title = 'Campbell Precinct 19-01 Precinct Committeewoman (Republican) (F)' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '22-01' WHERE LOWER(county) = 'campbell' AND title = 'Campbell Precinct 22-01 Precinct Committeeman (Democratic) (M)' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '22-01' WHERE LOWER(county) = 'campbell' AND title = 'Campbell Precinct 22-01 Precinct Committeeman (Republican) (M)' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '22-01' WHERE LOWER(county) = 'campbell' AND title = 'Campbell Precinct 22-01 Precinct Committeewoman (Democratic) (F)' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '22-01' WHERE LOWER(county) = 'campbell' AND title = 'Campbell Precinct 22-01 Precinct Committeewoman (Republican) (F)' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '23-01' WHERE LOWER(county) = 'campbell' AND title = 'Campbell Precinct 23-01 Precinct Committeeman (Democratic) (M)' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '23-01' WHERE LOWER(county) = 'campbell' AND title = 'Campbell Precinct 23-01 Precinct Committeeman (Republican) (M)' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '23-01' WHERE LOWER(county) = 'campbell' AND title = 'Campbell Precinct 23-01 Precinct Committeewoman (Democratic) (F)' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '23-01' WHERE LOWER(county) = 'campbell' AND title = 'Campbell Precinct 23-01 Precinct Committeewoman (Republican) (F)' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '24-01' WHERE LOWER(county) = 'campbell' AND title = 'Campbell Precinct 24-01 Precinct Committeeman (Democratic) (M)' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '24-01' WHERE LOWER(county) = 'campbell' AND title = 'Campbell Precinct 24-01 Precinct Committeeman (Republican) (M)' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '24-01' WHERE LOWER(county) = 'campbell' AND title = 'Campbell Precinct 24-01 Precinct Committeewoman (Democratic) (F)' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '24-01' WHERE LOWER(county) = 'campbell' AND title = 'Campbell Precinct 24-01 Precinct Committeewoman (Republican) (F)' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '26-01' WHERE LOWER(county) = 'campbell' AND title = 'Campbell Precinct 26-01 Precinct Committeeman (Democratic) (M)' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '26-01' WHERE LOWER(county) = 'campbell' AND title = 'Campbell Precinct 26-01 Precinct Committeeman (Republican) (M)' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '26-01' WHERE LOWER(county) = 'campbell' AND title = 'Campbell Precinct 26-01 Precinct Committeewoman (Democratic) (F)' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '26-01' WHERE LOWER(county) = 'campbell' AND title = 'Campbell Precinct 26-01 Precinct Committeewoman (Republican) (F)' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '15-1' WHERE LOWER(county) = 'carbon' AND title = 'Carbon Democratic Precinct Committeewoman Precinct 15-1' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '2-2' WHERE LOWER(county) = 'carbon' AND title = 'Carbon Democratic Precinct Committeewoman Precinct 2-2' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '3-2' WHERE LOWER(county) = 'carbon' AND title = 'Carbon Democratic Precinct Committeewoman Precinct 3-2' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '11-1' WHERE LOWER(county) = 'carbon' AND title = 'Carbon Republican Precinct Committeeman Precinct 11-1' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '14-01' WHERE LOWER(county) = 'carbon' AND title = 'Carbon Republican Precinct Committeeman Precinct 14-01' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '2-1' WHERE LOWER(county) = 'carbon' AND title = 'Carbon Republican Precinct Committeeman Precinct 2-1' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '2-2' WHERE LOWER(county) = 'carbon' AND title = 'Carbon Republican Precinct Committeeman Precinct 2-2' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '3-2' WHERE LOWER(county) = 'carbon' AND title = 'Carbon Republican Precinct Committeeman Precinct 3-2' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '5-1' WHERE LOWER(county) = 'carbon' AND title = 'Carbon Republican Precinct Committeeman Precinct 5-1' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '1-2' WHERE LOWER(county) = 'carbon' AND title = 'Carbon Republican Precinct Committeewoman Precinct 1-2' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '11-1' WHERE LOWER(county) = 'carbon' AND title = 'Carbon Republican Precinct Committeewoman Precinct 11-1' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '2-1' WHERE LOWER(county) = 'carbon' AND title = 'Carbon Republican Precinct Committeewoman Precinct 2-1' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '2-2' WHERE LOWER(county) = 'carbon' AND title = 'Carbon Republican Precinct Committeewoman Precinct 2-2' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '01-01' WHERE LOWER(county) = 'crook' AND title = 'Crook Precinct 01-01 Republican Precinct Committeeman' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '01-01' WHERE LOWER(county) = 'crook' AND title = 'Crook Precinct 01-01 Republican Precinct Committeewoman' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '01-02' WHERE LOWER(county) = 'crook' AND title = 'Crook Precinct 01-02 Republican Precinct Committeeman' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '01-02' WHERE LOWER(county) = 'crook' AND title = 'Crook Precinct 01-02 Republican Precinct Committeewoman' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '02-02' WHERE LOWER(county) = 'crook' AND title = 'Crook Precinct 02-02 Democrat Precinct Committeeman' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '02-02' WHERE LOWER(county) = 'crook' AND title = 'Crook Precinct 02-02 Republican Precinct Committeeman' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '02-02' WHERE LOWER(county) = 'crook' AND title = 'Crook Precinct 02-02 Republican Precinct Committeewoman' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '03-03' WHERE LOWER(county) = 'crook' AND title = 'Crook Precinct 03-03 Republican Precinct Committeeman' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '03-03' WHERE LOWER(county) = 'crook' AND title = 'Crook Precinct 03-03 Republican Precinct Committeewoman' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '07-07' WHERE LOWER(county) = 'crook' AND title = 'Crook Precinct 07-07 Republican Precinct Committeeman' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '07-07' WHERE LOWER(county) = 'crook' AND title = 'Crook Precinct 07-07 Republican Precinct Committeewoman' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '09-09' WHERE LOWER(county) = 'crook' AND title = 'Crook Precinct 09-09 Republican Precinct Committeeman' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '09-09' WHERE LOWER(county) = 'crook' AND title = 'Crook Precinct 09-09 Republican Precinct Committeewoman' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '11-11' WHERE LOWER(county) = 'crook' AND title = 'Crook Precinct 11-11 Republican Precinct Committeeman' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '11-11' WHERE LOWER(county) = 'crook' AND title = 'Crook Precinct 11-11 Republican Precinct Committeewoman' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '12-12' WHERE LOWER(county) = 'crook' AND title = 'Crook Precinct 12-12 Republican Precinct Committeeman' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '12-12' WHERE LOWER(county) = 'crook' AND title = 'Crook Precinct 12-12 Republican Precinct Committeewoman' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '13-13' WHERE LOWER(county) = 'crook' AND title = 'Crook Precinct 13-13 Republican Precinct Committeeman' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '13-13' WHERE LOWER(county) = 'crook' AND title = 'Crook Precinct 13-13 Republican Precinct Committeewoman' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '14-14' WHERE LOWER(county) = 'crook' AND title = 'Crook Precinct 14-14 Republican Precinct Committeeman' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '14-14' WHERE LOWER(county) = 'crook' AND title = 'Crook Precinct 14-14 Republican Precinct Committeewoman' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '15-15' WHERE LOWER(county) = 'crook' AND title = 'Crook Precinct 15-15 Republican Precinct Committeeman' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '15-15' WHERE LOWER(county) = 'crook' AND title = 'Crook Precinct 15-15 Republican Precinct Committeewoman' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '16-16' WHERE LOWER(county) = 'crook' AND title = 'Crook Precinct 16-16 Republican Precinct Committeeman' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '16-16' WHERE LOWER(county) = 'crook' AND title = 'Crook Precinct 16-16 Republican Precinct Committeewoman' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '18-01' WHERE LOWER(county) = 'crook' AND title = 'Crook Precinct 18-01 Republican Precinct Committeeman' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '18-01' WHERE LOWER(county) = 'crook' AND title = 'Crook Precinct 18-01 Republican Precinct Committeewoman' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '18-02' WHERE LOWER(county) = 'crook' AND title = 'Crook Precinct 18-02 Republican Precinct Committeeman' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '18-02' WHERE LOWER(county) = 'crook' AND title = 'Crook Precinct 18-02 Republican Precinct Committeewoman' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '23-23' WHERE LOWER(county) = 'crook' AND title = 'Crook Precinct 23-23 Republican Precinct Committeeman' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '23-23' WHERE LOWER(county) = 'crook' AND title = 'Crook Precinct 23-23 Republican Precinct Committeewoman' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '24-24' WHERE LOWER(county) = 'crook' AND title = 'Crook Precinct 24-24 Republican Precinct Committeeman' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '24-24' WHERE LOWER(county) = 'crook' AND title = 'Crook Precinct 24-24 Republican Precinct Committeewoman' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '26-26' WHERE LOWER(county) = 'crook' AND title = 'Crook Precinct 26-26 Republican Precinct Committeeman' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '26-26' WHERE LOWER(county) = 'crook' AND title = 'Crook Precinct 26-26 Republican Precinct Committeewoman' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '13-1' WHERE LOWER(county) = 'goshen' AND title = 'Goshen County Precinct 13-1 Democratic Precinct Committeewoman' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '13-1' WHERE LOWER(county) = 'goshen' AND title = 'Goshen County Precinct 13-1 Republican Precinct Committeeman' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '13-1' WHERE LOWER(county) = 'goshen' AND title = 'Goshen County Precinct 13-1 Republican Precinct Committeewoman' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '15-1' WHERE LOWER(county) = 'goshen' AND title = 'Goshen County Precinct 15-1 Republican Precinct Committeeman' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '15-1' WHERE LOWER(county) = 'goshen' AND title = 'Goshen County Precinct 15-1 Republican Precinct Committeewoman' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '16-1' WHERE LOWER(county) = 'goshen' AND title = 'Goshen County Precinct 16-1 Republican Precinct Committeeman' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '16-1' WHERE LOWER(county) = 'goshen' AND title = 'Goshen County Precinct 16-1 Republican Precinct Committeewoman' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '1' WHERE LOWER(county) = 'hot springs' AND title = 'East Thermopolis District 2-Precinct 1 2-1 Democratic Committeewoman (Democratic)' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '1' WHERE LOWER(county) = 'hot springs' AND title = 'East Thermopolis District 2-Precinct 1 2-1 Republican Committeewoman (Republican)' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '1' WHERE LOWER(county) = 'hot springs' AND title = 'Kirby District 3-Precinct 1 3-1 Democratic Committeewoman (Democratic)' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '1' WHERE LOWER(county) = 'hot springs' AND title = 'Rural District 4-Precinct 1 4-1 Democratic Committeeman (Democratic)' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '1' WHERE LOWER(county) = 'hot springs' AND title = 'Rural District 4-Precinct 1 4-1 Democratic Committeewoman (Democratic)' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '1' WHERE LOWER(county) = 'hot springs' AND title = 'Rural District 4-Precinct 1 4-1 Republican Committeeman (Republican)' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '1' WHERE LOWER(county) = 'hot springs' AND title = 'Rural District 4-Precinct 1 4-1 Republican Committeewoman (Republican)' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '1' WHERE LOWER(county) = 'hot springs' AND title = 'Thermopolis District 1-Precinct 1 1-1 Republican Committeewoman (Republican)' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '2' WHERE LOWER(county) = 'hot springs' AND title = 'Thermopolis District 1-Precinct 2 1-2 Democratic Committeewoman (Democratic)' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '2' WHERE LOWER(county) = 'hot springs' AND title = 'Thermopolis District 1-Precinct 2 1-2 Republican Committeeman (Republican)' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '2' WHERE LOWER(county) = 'hot springs' AND title = 'Thermopolis District 1-Precinct 2 1-2 Republican Committeewoman (Republican)' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '1-1' WHERE LOWER(county) = 'lincoln' AND title = 'Lincoln Precinct 1-1 Precinct Committeeman (Republican)' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '1-1' WHERE LOWER(county) = 'lincoln' AND title = 'Lincoln Precinct 1-1 Precinct Committeewoman (Republican)' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '2-1' WHERE LOWER(county) = 'lincoln' AND title = 'Lincoln Precinct 2-1 Precinct Committeeman (Republican)' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '2-1' WHERE LOWER(county) = 'lincoln' AND title = 'Lincoln Precinct 2-1 Precinct Committeewoman (Republican)' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '2-10' WHERE LOWER(county) = 'lincoln' AND title = 'Lincoln Precinct 2-10 Precinct Committeeman (Republican)' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '2-10' WHERE LOWER(county) = 'lincoln' AND title = 'Lincoln Precinct 2-10 Precinct Committeewoman (Republican)' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '2-3' WHERE LOWER(county) = 'lincoln' AND title = 'Lincoln Precinct 2-3 Precinct Committeeman (Republican)' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '2-3' WHERE LOWER(county) = 'lincoln' AND title = 'Lincoln Precinct 2-3 Precinct Committeewoman (Republican)' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '2-4' WHERE LOWER(county) = 'lincoln' AND title = 'Lincoln Precinct 2-4 Precinct Committeeman (Republican)' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '2-4' WHERE LOWER(county) = 'lincoln' AND title = 'Lincoln Precinct 2-4 Precinct Committeewoman (Republican)' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '2-5' WHERE LOWER(county) = 'lincoln' AND title = 'Lincoln Precinct 2-5 Precinct Committeeman (Republican)' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '2-5' WHERE LOWER(county) = 'lincoln' AND title = 'Lincoln Precinct 2-5 Precinct Committeewoman (Republican)' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '2-6' WHERE LOWER(county) = 'lincoln' AND title = 'Lincoln Precinct 2-6 Precinct Committeeman (Republican)' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '2-6' WHERE LOWER(county) = 'lincoln' AND title = 'Lincoln Precinct 2-6 Precinct Committeewoman (Republican)' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '2-7' WHERE LOWER(county) = 'lincoln' AND title = 'Lincoln Precinct 2-7 Precinct Committeeman (Republican)' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '2-7' WHERE LOWER(county) = 'lincoln' AND title = 'Lincoln Precinct 2-7 Precinct Committeewoman (Republican)' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '2-8' WHERE LOWER(county) = 'lincoln' AND title = 'Lincoln Precinct 2-8 Precinct Committeeman (Republican)' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '2-8' WHERE LOWER(county) = 'lincoln' AND title = 'Lincoln Precinct 2-8 Precinct Committeewoman (Republican)' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '2-9' WHERE LOWER(county) = 'lincoln' AND title = 'Lincoln Precinct 2-9 Precinct Committeeman (Republican)' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '2-9' WHERE LOWER(county) = 'lincoln' AND title = 'Lincoln Precinct 2-9 Precinct Committeewoman (Republican)' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '1-2' WHERE LOWER(county) = 'niobrara' AND title = 'Niobrara Precinct 1-2 Warren Republican Precinct Committeeman' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '1-2' WHERE LOWER(county) = 'niobrara' AND title = 'Niobrara Precinct 1-2 Warren Republican Precinct Committeewoman' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '3-2' WHERE LOWER(county) = 'niobrara' AND title = 'Niobrara Precinct 3-2 Hat Creek Republican Precinct Committeeman' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '3-2' WHERE LOWER(county) = 'niobrara' AND title = 'Niobrara Precinct 3-2 Hat Creek Republican Precinct Committeewoman' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '4-1' WHERE LOWER(county) = 'niobrara' AND title = 'Niobrara Precinct 4-1 Lance Creek Republican Precinct Committeewoman' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '6-1' WHERE LOWER(county) = 'niobrara' AND title = 'Niobrara Precinct 6-1 N. Lusk Republican Precinct Committeewoman' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '6-2' WHERE LOWER(county) = 'niobrara' AND title = 'Niobrara Precinct 6-2 S. Lusk Democrat Precinct Committeewoman' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '6-2' WHERE LOWER(county) = 'niobrara' AND title = 'Niobrara Precinct 6-2 S. Lusk Republican Precinct Committeeman' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '6-2' WHERE LOWER(county) = 'niobrara' AND title = 'Niobrara Precinct 6-2 S. Lusk Republican Precinct Committeewoman' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '7-1' WHERE LOWER(county) = 'niobrara' AND title = 'Niobrara Precinct 7-1 Manville Republican Precinct Committeewoman' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '1-1' WHERE LOWER(county) = 'platte' AND title = 'Platte 1-1 1F Democratic Precinct Committeeman' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '1-1' WHERE LOWER(county) = 'platte' AND title = 'Platte 1-1 1F Democratic Precinct Committeewoman' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '1-1' WHERE LOWER(county) = 'platte' AND title = 'Platte 1-1 1F Republican Precinct Committeeman' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '1-1' WHERE LOWER(county) = 'platte' AND title = 'Platte 1-1 1F Republican Precinct Committeewoman' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '1-2' WHERE LOWER(county) = 'platte' AND title = 'Platte 1-2 2F Democratic Precinct Committeeman' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '1-2' WHERE LOWER(county) = 'platte' AND title = 'Platte 1-2 2F Democratic Precinct Committeewoman' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '1-2' WHERE LOWER(county) = 'platte' AND title = 'Platte 1-2 2F Republican Precinct Committeeman' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '1-2' WHERE LOWER(county) = 'platte' AND title = 'Platte 1-2 2F Republican Precinct Committeewoman' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '1-3' WHERE LOWER(county) = 'platte' AND title = 'Platte 1-3 Antelope Gap Democratic Precinct Committeeman' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '1-3' WHERE LOWER(county) = 'platte' AND title = 'Platte 1-3 Antelope Gap Democratic Precinct Committeewoman' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '1-3' WHERE LOWER(county) = 'platte' AND title = 'Platte 1-3 Antelope Gap Republican Precinct Committeeman' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '1-3' WHERE LOWER(county) = 'platte' AND title = 'Platte 1-3 Antelope Gap Republican Precinct Committeewoman' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '1-6' WHERE LOWER(county) = 'platte' AND title = 'Platte 1-6 Wheatland Town Democratic Precinct Committeeman' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '1-6' WHERE LOWER(county) = 'platte' AND title = 'Platte 1-6 Wheatland Town Democratic Precinct Committeewoman' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '1-6' WHERE LOWER(county) = 'platte' AND title = 'Platte 1-6 Wheatland Town Republican Precinct Committeeman' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '1-6' WHERE LOWER(county) = 'platte' AND title = 'Platte 1-6 Wheatland Town Republican Precinct Committeewoman' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '2-1' WHERE LOWER(county) = 'platte' AND title = 'Platte 2-1 Guernsey Town Democratic Precinct Committeeman' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '2-1' WHERE LOWER(county) = 'platte' AND title = 'Platte 2-1 Guernsey Town Democratic Precinct Committeewoman' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '2-1' WHERE LOWER(county) = 'platte' AND title = 'Platte 2-1 Guernsey Town Republican Precinct Committeeman' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '2-1' WHERE LOWER(county) = 'platte' AND title = 'Platte 2-1 Guernsey Town Republican Precinct Committeewoman' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '2-2' WHERE LOWER(county) = 'platte' AND title = 'Platte 2-2 Sunrise Democratic Precinct Committeeman' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '2-2' WHERE LOWER(county) = 'platte' AND title = 'Platte 2-2 Sunrise Democratic Precinct Committeewoman' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '2-2' WHERE LOWER(county) = 'platte' AND title = 'Platte 2-2 Sunrise Republican Precinct Committeeman' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '2-2' WHERE LOWER(county) = 'platte' AND title = 'Platte 2-2 Sunrise Republican Precinct Committeewoman' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '3-1' WHERE LOWER(county) = 'platte' AND title = 'Platte 3-1 Glendo Democratic Precinct Committeeman' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '3-1' WHERE LOWER(county) = 'platte' AND title = 'Platte 3-1 Glendo Democratic Precinct Committeewoman' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '3-1' WHERE LOWER(county) = 'platte' AND title = 'Platte 3-1 Glendo Republican Precinct Committeeman' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '3-1' WHERE LOWER(county) = 'platte' AND title = 'Platte 3-1 Glendo Republican Precinct Committeewoman' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '4-1' WHERE LOWER(county) = 'platte' AND title = 'Platte 4-1 Chugwater Democratic Precinct Committeeman' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '4-1' WHERE LOWER(county) = 'platte' AND title = 'Platte 4-1 Chugwater Democratic Precinct Committeewoman' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '4-1' WHERE LOWER(county) = 'platte' AND title = 'Platte 4-1 Chugwater Republican Precinct Committeeman' AND precinct_code IS NULL;
UPDATE offices SET precinct_code = '4-1' WHERE LOWER(county) = 'platte' AND title = 'Platte 4-1 Chugwater Republican Precinct Committeewoman' AND precinct_code IS NULL;
