-- Laramie County offices.precinct_code correction: SOS sequential IDs → CLK 'N-N' format.
-- Generated by geocoding one candidate address per SOS precinct and querying the CLK ArcGIS layer.
-- SOS 46115 (Chugwater) omitted — outside CLK polygon coverage area; no polygon lookup possible.
-- Collisions: 46024+46086 → 3-5; 46113+46123 → 4-11 (verified multiple addresses).

UPDATE offices SET precinct_code = '1-1' WHERE LOWER(county) = 'laramie' AND precinct_code = '46023';
UPDATE offices SET precinct_code = '3-5' WHERE LOWER(county) = 'laramie' AND precinct_code = '46024';
UPDATE offices SET precinct_code = '1-3' WHERE LOWER(county) = 'laramie' AND precinct_code = '46025';
UPDATE offices SET precinct_code = '1-4' WHERE LOWER(county) = 'laramie' AND precinct_code = '46026';
UPDATE offices SET precinct_code = '1-5' WHERE LOWER(county) = 'laramie' AND precinct_code = '46027';
UPDATE offices SET precinct_code = '1-6' WHERE LOWER(county) = 'laramie' AND precinct_code = '46028';
UPDATE offices SET precinct_code = '2-1' WHERE LOWER(county) = 'laramie' AND precinct_code = '46054';
UPDATE offices SET precinct_code = '2-2' WHERE LOWER(county) = 'laramie' AND precinct_code = '46055';
UPDATE offices SET precinct_code = '2-3' WHERE LOWER(county) = 'laramie' AND precinct_code = '46056';
UPDATE offices SET precinct_code = '2-4' WHERE LOWER(county) = 'laramie' AND precinct_code = '46057';
UPDATE offices SET precinct_code = '2-6' WHERE LOWER(county) = 'laramie' AND precinct_code = '46059';
UPDATE offices SET precinct_code = '2-7' WHERE LOWER(county) = 'laramie' AND precinct_code = '46060';
UPDATE offices SET precinct_code = '2-8' WHERE LOWER(county) = 'laramie' AND precinct_code = '46061';
UPDATE offices SET precinct_code = '3-2' WHERE LOWER(county) = 'laramie' AND precinct_code = '46083';
UPDATE offices SET precinct_code = '3-3' WHERE LOWER(county) = 'laramie' AND precinct_code = '46084';
UPDATE offices SET precinct_code = '3-4' WHERE LOWER(county) = 'laramie' AND precinct_code = '46085';
UPDATE offices SET precinct_code = '3-5' WHERE LOWER(county) = 'laramie' AND precinct_code = '46086';
UPDATE offices SET precinct_code = '3-6' WHERE LOWER(county) = 'laramie' AND precinct_code = '46087';
UPDATE offices SET precinct_code = '3-7' WHERE LOWER(county) = 'laramie' AND precinct_code = '46088';
UPDATE offices SET precinct_code = '4-11' WHERE LOWER(county) = 'laramie' AND precinct_code = '46113';
UPDATE offices SET precinct_code = '4-2' WHERE LOWER(county) = 'laramie' AND precinct_code = '46114';
UPDATE offices SET precinct_code = '4-4' WHERE LOWER(county) = 'laramie' AND precinct_code = '46116';
UPDATE offices SET precinct_code = '4-5' WHERE LOWER(county) = 'laramie' AND precinct_code = '46117';
UPDATE offices SET precinct_code = '4-6' WHERE LOWER(county) = 'laramie' AND precinct_code = '46118';
UPDATE offices SET precinct_code = '4-7' WHERE LOWER(county) = 'laramie' AND precinct_code = '46119';
UPDATE offices SET precinct_code = '4-8' WHERE LOWER(county) = 'laramie' AND precinct_code = '46120';
UPDATE offices SET precinct_code = '4-9' WHERE LOWER(county) = 'laramie' AND precinct_code = '46121';
UPDATE offices SET precinct_code = '4-10' WHERE LOWER(county) = 'laramie' AND precinct_code = '46122';
UPDATE offices SET precinct_code = '4-11' WHERE LOWER(county) = 'laramie' AND precinct_code = '46123';
UPDATE offices SET precinct_code = '5-1' WHERE LOWER(county) = 'laramie' AND precinct_code = '46143';
UPDATE offices SET precinct_code = '5-2' WHERE LOWER(county) = 'laramie' AND precinct_code = '46144';
UPDATE offices SET precinct_code = '5-3' WHERE LOWER(county) = 'laramie' AND precinct_code = '46145';
UPDATE offices SET precinct_code = '5-4' WHERE LOWER(county) = 'laramie' AND precinct_code = '46146';
