#!/usr/bin/env node
// scripts/generate_enrichment_sql.mjs
// Reads all available enhanced batch CSVs and generates
// db/seed/002_enrichment_updates.sql — safe to re-run.
//
// Run: node scripts/generate_enrichment_sql.mjs

import { readFileSync, writeFileSync, readdirSync } from 'node:fs';
import { join } from 'node:path';

const SEED_DIR = 'db/seed';
const OUT = 'db/seed/002_enrichment_updates.sql';

// ── CSV parser (handles quoted fields with embedded commas and "" escapes) ──
function parseCSV(text) {
  const rows = [];
  let row = [], field = '', inQ = false;
  for (let i = 0; i < text.length; i++) {
    const c = text[i], n = text[i + 1];
    if (inQ) {
      if (c === '"' && n === '"') { field += '"'; i++; }
      else if (c === '"') { inQ = false; }
      else { field += c; }
    } else {
      if (c === '"') { inQ = true; }
      else if (c === ',') { row.push(field); field = ''; }
      else if (c === '\r' && n === '\n') { row.push(field); rows.push(row); row = []; field = ''; i++; }
      else if (c === '\n') { row.push(field); rows.push(row); row = []; field = ''; }
      else { field += c; }
    }
  }
  if (field || row.length) { row.push(field); if (row.some(f => f)) rows.push(row); }
  return rows;
}

function esc(v) {
  if (!v || !v.trim()) return null;
  return "'" + v.trim().replace(/'/g, "''") + "'";
}

// ── Collect batch files ──────────────────────────────────────────────────────
const files = readdirSync(SEED_DIR)
  .filter(f => /^wy_2026_primary_candidates_enhanced_batch\d+_rows/.test(f))
  .sort()
  .map(f => join(SEED_DIR, f));

console.log(`Found ${files.length} batch file(s):`);
files.forEach(f => console.log(' ', f.split('/').pop()));

let headers = null;
// slug → merged field map (later batches win on non-empty values)
const bySlug = new Map();

for (const file of files) {
  const rows = parseCSV(readFileSync(file, 'utf-8'));
  if (!headers) {
    headers = rows[0];
    console.log(`Schema: ${headers.length} columns`);
  }
  const hdr = rows[0];
  const idx = name => hdr.indexOf(name);

  for (let i = 1; i < rows.length; i++) {
    const r = rows[i];
    if (r.length < 2) continue;
    const slug = (r[idx('candidate_slug')] || '').trim();
    if (!slug) continue;

    const existing = bySlug.get(slug) || {};

    // Helper: take new value if non-empty, else keep existing
    const take = (col, key = col) => {
      const v = (r[idx(col)] || '').trim();
      if (v) existing[key] = v;
    };
    const takeFallback = (primary, fallback, key) => {
      const v = (r[idx(primary)] || '').trim() || (r[idx(fallback)] || '').trim();
      if (v) existing[key] = v;
    };

    // Existing schema fields
    take('candidate_homepage_url', 'website_url');
    take('thumbnail_asset_path', 'photo_url');
    take('short_bio', 'summary');
    take('occupation');
    take('hometown_or_residence', 'hometown');
    takeFallback('campaign_facebook_url', 'facebook_url', 'facebook_url');
    takeFallback('campaign_x_url', 'x_url', 'twitter_url');
    takeFallback('campaign_instagram_url', 'instagram_url', 'instagram_url');
    takeFallback('campaign_youtube_url', 'youtube_url', 'youtube_url');
    takeFallback('fec_candidate_url', 'campaign_finance_summary_url', 'campaign_finance_url');

    // New enrichment fields
    takeFallback('campaign_linkedin_url', 'linkedin_url', 'linkedin_url');
    take('fec_candidate_id');
    take('fec_committee_id');
    take('fec_candidate_url');
    take('fec_committee_url');
    take('wycfis_candidate_url');
    take('wycfis_committee_url');
    take('top_issues');
    take('incumbency_status');
    take('current_office');
    take('public_statement_url');
    take('candidate_page_path');
    take('race_slug');
    take('race_display');
    take('official_office_url');
    take('official_office_facebook_url');
    take('official_office_x_url');
    take('thumbnail_source_url');
    take('thumbnail_permission_status');
    take('data_confidence_overall', 'data_confidence');
    take('enrichment_notes');
    take('enrichment_batch');
    take('batch_status');

    // human_review_needed: Yes/No → 1/0
    const hrv = (r[idx('human_review_needed')] || '').trim();
    if (hrv === 'Yes') existing['human_review_needed'] = '1';
    else if (hrv === 'No') existing['human_review_needed'] = '0';

    bySlug.set(slug, existing);
  }
}

console.log(`Merged data for ${bySlug.size} candidates`);

// ── Generate SQL ─────────────────────────────────────────────────────────────
const INT_FIELDS = new Set(['human_review_needed']);
const lines = [
  '-- 002_enrichment_updates.sql',
  '-- Auto-generated by scripts/generate_enrichment_sql.mjs',
  '-- Do not edit by hand — re-run the generator when new batch CSVs arrive.',
  '-- Safe to re-run: only non-empty values are written.',
  '',
];

let count = 0;
for (const [slug, fields] of bySlug) {
  const sets = [];
  for (const [col, val] of Object.entries(fields)) {
    if (INT_FIELDS.has(col)) {
      sets.push(`  ${col} = ${val}`);
    } else {
      const escaped = esc(val);
      if (escaped) sets.push(`  ${col} = ${escaped}`);
    }
  }
  if (sets.length === 0) continue;
  sets.push(`  updated_at = datetime('now')`);
  lines.push(`UPDATE candidates SET`);
  lines.push(sets.join(',\n'));
  lines.push(`WHERE slug = '${slug}';`);
  lines.push('');
  count++;
}

writeFileSync(OUT, lines.join('\n'), 'utf-8');
console.log(`\nWrote ${count} UPDATE statements → ${OUT}`);
